// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IngestionProcessorMetrics is an autogenerated mock type for the IngestionProcessorMetrics type
type IngestionProcessorMetrics struct {
	mock.Mock
}

type IngestionProcessorMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *IngestionProcessorMetrics) EXPECT() *IngestionProcessorMetrics_Expecter {
	return &IngestionProcessorMetrics_Expecter{mock: &_m.Mock}
}

// RecordChangeSetApply provides a mock function with given fields: ctx, success, changes
func (_m *IngestionProcessorMetrics) RecordChangeSetApply(ctx context.Context, success bool, changes int64) {
	_m.Called(ctx, success, changes)
}

// IngestionProcessorMetrics_RecordChangeSetApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordChangeSetApply'
type IngestionProcessorMetrics_RecordChangeSetApply_Call struct {
	*mock.Call
}

// RecordChangeSetApply is a helper method to define mock.On call
//   - ctx context.Context
//   - success bool
//   - changes int64
func (_e *IngestionProcessorMetrics_Expecter) RecordChangeSetApply(ctx interface{}, success interface{}, changes interface{}) *IngestionProcessorMetrics_RecordChangeSetApply_Call {
	return &IngestionProcessorMetrics_RecordChangeSetApply_Call{Call: _e.mock.On("RecordChangeSetApply", ctx, success, changes)}
}

func (_c *IngestionProcessorMetrics_RecordChangeSetApply_Call) Run(run func(ctx context.Context, success bool, changes int64)) *IngestionProcessorMetrics_RecordChangeSetApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(int64))
	})
	return _c
}

func (_c *IngestionProcessorMetrics_RecordChangeSetApply_Call) Return() *IngestionProcessorMetrics_RecordChangeSetApply_Call {
	_c.Call.Return()
	return _c
}

func (_c *IngestionProcessorMetrics_RecordChangeSetApply_Call) RunAndReturn(run func(context.Context, bool, int64)) *IngestionProcessorMetrics_RecordChangeSetApply_Call {
	_c.Run(run)
	return _c
}

// RecordChangeSetCreate provides a mock function with given fields: ctx, success, changes
func (_m *IngestionProcessorMetrics) RecordChangeSetCreate(ctx context.Context, success bool, changes int64) {
	_m.Called(ctx, success, changes)
}

// IngestionProcessorMetrics_RecordChangeSetCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordChangeSetCreate'
type IngestionProcessorMetrics_RecordChangeSetCreate_Call struct {
	*mock.Call
}

// RecordChangeSetCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - success bool
//   - changes int64
func (_e *IngestionProcessorMetrics_Expecter) RecordChangeSetCreate(ctx interface{}, success interface{}, changes interface{}) *IngestionProcessorMetrics_RecordChangeSetCreate_Call {
	return &IngestionProcessorMetrics_RecordChangeSetCreate_Call{Call: _e.mock.On("RecordChangeSetCreate", ctx, success, changes)}
}

func (_c *IngestionProcessorMetrics_RecordChangeSetCreate_Call) Run(run func(ctx context.Context, success bool, changes int64)) *IngestionProcessorMetrics_RecordChangeSetCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(int64))
	})
	return _c
}

func (_c *IngestionProcessorMetrics_RecordChangeSetCreate_Call) Return() *IngestionProcessorMetrics_RecordChangeSetCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *IngestionProcessorMetrics_RecordChangeSetCreate_Call) RunAndReturn(run func(context.Context, bool, int64)) *IngestionProcessorMetrics_RecordChangeSetCreate_Call {
	_c.Run(run)
	return _c
}

// RecordHandleMessage provides a mock function with given fields: ctx, success
func (_m *IngestionProcessorMetrics) RecordHandleMessage(ctx context.Context, success bool) {
	_m.Called(ctx, success)
}

// IngestionProcessorMetrics_RecordHandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordHandleMessage'
type IngestionProcessorMetrics_RecordHandleMessage_Call struct {
	*mock.Call
}

// RecordHandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - success bool
func (_e *IngestionProcessorMetrics_Expecter) RecordHandleMessage(ctx interface{}, success interface{}) *IngestionProcessorMetrics_RecordHandleMessage_Call {
	return &IngestionProcessorMetrics_RecordHandleMessage_Call{Call: _e.mock.On("RecordHandleMessage", ctx, success)}
}

func (_c *IngestionProcessorMetrics_RecordHandleMessage_Call) Run(run func(ctx context.Context, success bool)) *IngestionProcessorMetrics_RecordHandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *IngestionProcessorMetrics_RecordHandleMessage_Call) Return() *IngestionProcessorMetrics_RecordHandleMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *IngestionProcessorMetrics_RecordHandleMessage_Call) RunAndReturn(run func(context.Context, bool)) *IngestionProcessorMetrics_RecordHandleMessage_Call {
	_c.Run(run)
	return _c
}

// RecordIngestionLogCreate provides a mock function with given fields: ctx, success
func (_m *IngestionProcessorMetrics) RecordIngestionLogCreate(ctx context.Context, success bool) {
	_m.Called(ctx, success)
}

// IngestionProcessorMetrics_RecordIngestionLogCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIngestionLogCreate'
type IngestionProcessorMetrics_RecordIngestionLogCreate_Call struct {
	*mock.Call
}

// RecordIngestionLogCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - success bool
func (_e *IngestionProcessorMetrics_Expecter) RecordIngestionLogCreate(ctx interface{}, success interface{}) *IngestionProcessorMetrics_RecordIngestionLogCreate_Call {
	return &IngestionProcessorMetrics_RecordIngestionLogCreate_Call{Call: _e.mock.On("RecordIngestionLogCreate", ctx, success)}
}

func (_c *IngestionProcessorMetrics_RecordIngestionLogCreate_Call) Run(run func(ctx context.Context, success bool)) *IngestionProcessorMetrics_RecordIngestionLogCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *IngestionProcessorMetrics_RecordIngestionLogCreate_Call) Return() *IngestionProcessorMetrics_RecordIngestionLogCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *IngestionProcessorMetrics_RecordIngestionLogCreate_Call) RunAndReturn(run func(context.Context, bool)) *IngestionProcessorMetrics_RecordIngestionLogCreate_Call {
	_c.Run(run)
	return _c
}

// NewIngestionProcessorMetrics creates a new instance of IngestionProcessorMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestionProcessorMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestionProcessorMetrics {
	mock := &IngestionProcessorMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
