// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	netboxdiodeplugin "github.com/netboxlabs/diode/diode-server/netboxdiodeplugin"
	mock "github.com/stretchr/testify/mock"

	ops "github.com/netboxlabs/diode/diode-server/reconciler/ops"

	changeset "github.com/netboxlabs/diode/diode-server/reconciler/changeset"

	reconcilerpb "github.com/netboxlabs/diode/diode-server/gen/diode/v1/reconcilerpb"
)

// IngestionProcessorOps is an autogenerated mock type for the IngestionProcessorOps type
type IngestionProcessorOps struct {
	mock.Mock
}

type IngestionProcessorOps_Expecter struct {
	mock *mock.Mock
}

func (_m *IngestionProcessorOps) EXPECT() *IngestionProcessorOps_Expecter {
	return &IngestionProcessorOps_Expecter{mock: &_m.Mock}
}

// BulkCreateIngestionLogs provides a mock function with given fields: ctx, ingestionLogs, sourceMetadata, entityHashes
func (_m *IngestionProcessorOps) BulkCreateIngestionLogs(ctx context.Context, ingestionLogs []*reconcilerpb.IngestionLog, sourceMetadata [][]byte, entityHashes []string) ([]*ops.CreateIngestionLogResult, error) {
	ret := _m.Called(ctx, ingestionLogs, sourceMetadata, entityHashes)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreateIngestionLogs")
	}

	var r0 []*ops.CreateIngestionLogResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*reconcilerpb.IngestionLog, [][]byte, []string) ([]*ops.CreateIngestionLogResult, error)); ok {
		return rf(ctx, ingestionLogs, sourceMetadata, entityHashes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*reconcilerpb.IngestionLog, [][]byte, []string) []*ops.CreateIngestionLogResult); ok {
		r0 = rf(ctx, ingestionLogs, sourceMetadata, entityHashes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ops.CreateIngestionLogResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*reconcilerpb.IngestionLog, [][]byte, []string) error); ok {
		r1 = rf(ctx, ingestionLogs, sourceMetadata, entityHashes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngestionProcessorOps_BulkCreateIngestionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreateIngestionLogs'
type IngestionProcessorOps_BulkCreateIngestionLogs_Call struct {
	*mock.Call
}

// BulkCreateIngestionLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLogs []*reconcilerpb.IngestionLog
//   - sourceMetadata [][]byte
//   - entityHashes []string
func (_e *IngestionProcessorOps_Expecter) BulkCreateIngestionLogs(ctx interface{}, ingestionLogs interface{}, sourceMetadata interface{}, entityHashes interface{}) *IngestionProcessorOps_BulkCreateIngestionLogs_Call {
	return &IngestionProcessorOps_BulkCreateIngestionLogs_Call{Call: _e.mock.On("BulkCreateIngestionLogs", ctx, ingestionLogs, sourceMetadata, entityHashes)}
}

func (_c *IngestionProcessorOps_BulkCreateIngestionLogs_Call) Run(run func(ctx context.Context, ingestionLogs []*reconcilerpb.IngestionLog, sourceMetadata [][]byte, entityHashes []string)) *IngestionProcessorOps_BulkCreateIngestionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*reconcilerpb.IngestionLog), args[2].([][]byte), args[3].([]string))
	})
	return _c
}

func (_c *IngestionProcessorOps_BulkCreateIngestionLogs_Call) Return(_a0 []*ops.CreateIngestionLogResult, _a1 error) *IngestionProcessorOps_BulkCreateIngestionLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngestionProcessorOps_BulkCreateIngestionLogs_Call) RunAndReturn(run func(context.Context, []*reconcilerpb.IngestionLog, [][]byte, []string) ([]*ops.CreateIngestionLogResult, error)) *IngestionProcessorOps_BulkCreateIngestionLogs_Call {
	_c.Call.Return(run)
	return _c
}

// BulkPlan provides a mock function with given fields: ctx, items, branchID
func (_m *IngestionProcessorOps) BulkPlan(ctx context.Context, items []ops.QueuedIngestionLog, branchID string) []ops.BulkGenerateChangeSetResult {
	ret := _m.Called(ctx, items, branchID)

	if len(ret) == 0 {
		panic("no return value specified for BulkPlan")
	}

	var r0 []ops.BulkGenerateChangeSetResult
	if rf, ok := ret.Get(0).(func(context.Context, []ops.QueuedIngestionLog, string) []ops.BulkGenerateChangeSetResult); ok {
		r0 = rf(ctx, items, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ops.BulkGenerateChangeSetResult)
		}
	}

	return r0
}

// IngestionProcessorOps_BulkPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkPlan'
type IngestionProcessorOps_BulkPlan_Call struct {
	*mock.Call
}

// BulkPlan is a helper method to define mock.On call
//   - ctx context.Context
//   - items []ops.QueuedIngestionLog
//   - branchID string
func (_e *IngestionProcessorOps_Expecter) BulkPlan(ctx interface{}, items interface{}, branchID interface{}) *IngestionProcessorOps_BulkPlan_Call {
	return &IngestionProcessorOps_BulkPlan_Call{Call: _e.mock.On("BulkPlan", ctx, items, branchID)}
}

func (_c *IngestionProcessorOps_BulkPlan_Call) Run(run func(ctx context.Context, items []ops.QueuedIngestionLog, branchID string)) *IngestionProcessorOps_BulkPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]ops.QueuedIngestionLog), args[2].(string))
	})
	return _c
}

func (_c *IngestionProcessorOps_BulkPlan_Call) Return(_a0 []ops.BulkGenerateChangeSetResult) *IngestionProcessorOps_BulkPlan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngestionProcessorOps_BulkPlan_Call) RunAndReturn(run func(context.Context, []ops.QueuedIngestionLog, string) []ops.BulkGenerateChangeSetResult) *IngestionProcessorOps_BulkPlan_Call {
	_c.Call.Return(run)
	return _c
}

// BulkPlanApply provides a mock function with given fields: ctx, items, branchID
func (_m *IngestionProcessorOps) BulkPlanApply(ctx context.Context, items []ops.QueuedIngestionLog, branchID string) []ops.BulkPlanApplyResult {
	ret := _m.Called(ctx, items, branchID)

	if len(ret) == 0 {
		panic("no return value specified for BulkPlanApply")
	}

	var r0 []ops.BulkPlanApplyResult
	if rf, ok := ret.Get(0).(func(context.Context, []ops.QueuedIngestionLog, string) []ops.BulkPlanApplyResult); ok {
		r0 = rf(ctx, items, branchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ops.BulkPlanApplyResult)
		}
	}

	return r0
}

// IngestionProcessorOps_BulkPlanApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkPlanApply'
type IngestionProcessorOps_BulkPlanApply_Call struct {
	*mock.Call
}

// BulkPlanApply is a helper method to define mock.On call
//   - ctx context.Context
//   - items []ops.QueuedIngestionLog
//   - branchID string
func (_e *IngestionProcessorOps_Expecter) BulkPlanApply(ctx interface{}, items interface{}, branchID interface{}) *IngestionProcessorOps_BulkPlanApply_Call {
	return &IngestionProcessorOps_BulkPlanApply_Call{Call: _e.mock.On("BulkPlanApply", ctx, items, branchID)}
}

func (_c *IngestionProcessorOps_BulkPlanApply_Call) Run(run func(ctx context.Context, items []ops.QueuedIngestionLog, branchID string)) *IngestionProcessorOps_BulkPlanApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]ops.QueuedIngestionLog), args[2].(string))
	})
	return _c
}

func (_c *IngestionProcessorOps_BulkPlanApply_Call) Return(_a0 []ops.BulkPlanApplyResult) *IngestionProcessorOps_BulkPlanApply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngestionProcessorOps_BulkPlanApply_Call) RunAndReturn(run func(context.Context, []ops.QueuedIngestionLog, string) []ops.BulkPlanApplyResult) *IngestionProcessorOps_BulkPlanApply_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIngestionLog provides a mock function with given fields: ctx, ingestionLog, sourceMetadata
func (_m *IngestionProcessorOps) CreateIngestionLog(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte) (*ops.CreateIngestionLogResult, error) {
	ret := _m.Called(ctx, ingestionLog, sourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionLog")
	}

	var r0 *ops.CreateIngestionLogResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte) (*ops.CreateIngestionLogResult, error)); ok {
		return rf(ctx, ingestionLog, sourceMetadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte) *ops.CreateIngestionLogResult); ok {
		r0 = rf(ctx, ingestionLog, sourceMetadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ops.CreateIngestionLogResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.IngestionLog, []byte) error); ok {
		r1 = rf(ctx, ingestionLog, sourceMetadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngestionProcessorOps_CreateIngestionLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionLog'
type IngestionProcessorOps_CreateIngestionLog_Call struct {
	*mock.Call
}

// CreateIngestionLog is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLog *reconcilerpb.IngestionLog
//   - sourceMetadata []byte
func (_e *IngestionProcessorOps_Expecter) CreateIngestionLog(ctx interface{}, ingestionLog interface{}, sourceMetadata interface{}) *IngestionProcessorOps_CreateIngestionLog_Call {
	return &IngestionProcessorOps_CreateIngestionLog_Call{Call: _e.mock.On("CreateIngestionLog", ctx, ingestionLog, sourceMetadata)}
}

func (_c *IngestionProcessorOps_CreateIngestionLog_Call) Run(run func(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte)) *IngestionProcessorOps_CreateIngestionLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.IngestionLog), args[2].([]byte))
	})
	return _c
}

func (_c *IngestionProcessorOps_CreateIngestionLog_Call) Return(_a0 *ops.CreateIngestionLogResult, _a1 error) *IngestionProcessorOps_CreateIngestionLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngestionProcessorOps_CreateIngestionLog_Call) RunAndReturn(run func(context.Context, *reconcilerpb.IngestionLog, []byte) (*ops.CreateIngestionLogResult, error)) *IngestionProcessorOps_CreateIngestionLog_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultBranch provides a mock function with given fields: ctx
func (_m *IngestionProcessorOps) DefaultBranch(ctx context.Context) (*netboxdiodeplugin.Branch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DefaultBranch")
	}

	var r0 *netboxdiodeplugin.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*netboxdiodeplugin.Branch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *netboxdiodeplugin.Branch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netboxdiodeplugin.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngestionProcessorOps_DefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultBranch'
type IngestionProcessorOps_DefaultBranch_Call struct {
	*mock.Call
}

// DefaultBranch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IngestionProcessorOps_Expecter) DefaultBranch(ctx interface{}) *IngestionProcessorOps_DefaultBranch_Call {
	return &IngestionProcessorOps_DefaultBranch_Call{Call: _e.mock.On("DefaultBranch", ctx)}
}

func (_c *IngestionProcessorOps_DefaultBranch_Call) Run(run func(ctx context.Context)) *IngestionProcessorOps_DefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IngestionProcessorOps_DefaultBranch_Call) Return(_a0 *netboxdiodeplugin.Branch, _a1 error) *IngestionProcessorOps_DefaultBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngestionProcessorOps_DefaultBranch_Call) RunAndReturn(run func(context.Context) (*netboxdiodeplugin.Branch, error)) *IngestionProcessorOps_DefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshDefaultBranch provides a mock function with given fields: ctx
func (_m *IngestionProcessorOps) RefreshDefaultBranch(ctx context.Context) (*netboxdiodeplugin.Branch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RefreshDefaultBranch")
	}

	var r0 *netboxdiodeplugin.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*netboxdiodeplugin.Branch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *netboxdiodeplugin.Branch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netboxdiodeplugin.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngestionProcessorOps_RefreshDefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshDefaultBranch'
type IngestionProcessorOps_RefreshDefaultBranch_Call struct {
	*mock.Call
}

// RefreshDefaultBranch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IngestionProcessorOps_Expecter) RefreshDefaultBranch(ctx interface{}) *IngestionProcessorOps_RefreshDefaultBranch_Call {
	return &IngestionProcessorOps_RefreshDefaultBranch_Call{Call: _e.mock.On("RefreshDefaultBranch", ctx)}
}

func (_c *IngestionProcessorOps_RefreshDefaultBranch_Call) Run(run func(ctx context.Context)) *IngestionProcessorOps_RefreshDefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IngestionProcessorOps_RefreshDefaultBranch_Call) Return(_a0 *netboxdiodeplugin.Branch, _a1 error) *IngestionProcessorOps_RefreshDefaultBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngestionProcessorOps_RefreshDefaultBranch_Call) RunAndReturn(run func(context.Context) (*netboxdiodeplugin.Branch, error)) *IngestionProcessorOps_RefreshDefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyChangeSetForLog provides a mock function with given fields: ctx, item, cs, branchID
func (_m *IngestionProcessorOps) ApplyChangeSetForLog(ctx context.Context, item ops.QueuedIngestionLog, cs *changeset.ChangeSet, branchID string) error {
	ret := _m.Called(ctx, item, cs, branchID)

	if len(ret) == 0 {
		panic("no return value specified for ApplyChangeSetForLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ops.QueuedIngestionLog, *changeset.ChangeSet, string) error); ok {
		r0 = rf(ctx, item, cs, branchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngestionProcessorOps_ApplyChangeSetForLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyChangeSetForLog'
type IngestionProcessorOps_ApplyChangeSetForLog_Call struct {
	*mock.Call
}

// ApplyChangeSetForLog is a helper method to define mock.On call
//   - ctx context.Context
//   - item ops.QueuedIngestionLog
//   - cs *changeset.ChangeSet
//   - branchID string
func (_e *IngestionProcessorOps_Expecter) ApplyChangeSetForLog(ctx interface{}, item interface{}, cs interface{}, branchID interface{}) *IngestionProcessorOps_ApplyChangeSetForLog_Call {
	return &IngestionProcessorOps_ApplyChangeSetForLog_Call{Call: _e.mock.On("ApplyChangeSetForLog", ctx, item, cs, branchID)}
}

func (_c *IngestionProcessorOps_ApplyChangeSetForLog_Call) Run(run func(ctx context.Context, item ops.QueuedIngestionLog, cs *changeset.ChangeSet, branchID string)) *IngestionProcessorOps_ApplyChangeSetForLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ops.QueuedIngestionLog), args[2].(*changeset.ChangeSet), args[3].(string))
	})
	return _c
}

func (_c *IngestionProcessorOps_ApplyChangeSetForLog_Call) Return(_a0 error) *IngestionProcessorOps_ApplyChangeSetForLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngestionProcessorOps_ApplyChangeSetForLog_Call) RunAndReturn(run func(context.Context, ops.QueuedIngestionLog, *changeset.ChangeSet, string) error) *IngestionProcessorOps_ApplyChangeSetForLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngestionProcessorOps creates a new instance of IngestionProcessorOps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestionProcessorOps(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestionProcessorOps {
	mock := &IngestionProcessorOps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
