// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reconcilerpb "github.com/netboxlabs/diode/diode-server/gen/diode/v1/reconcilerpb"
)

// IngestionLogRepository is an autogenerated mock type for the IngestionLogRepository type
type IngestionLogRepository struct {
	mock.Mock
}

type IngestionLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IngestionLogRepository) EXPECT() *IngestionLogRepository_Expecter {
	return &IngestionLogRepository_Expecter{mock: &_m.Mock}
}

// CreateIngestionLog provides a mock function with given fields: ctx, ingestionLog, sourceMetadata
func (_m *IngestionLogRepository) CreateIngestionLog(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte) error {
	ret := _m.Called(ctx, ingestionLog, sourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte) error); ok {
		r0 = rf(ctx, ingestionLog, sourceMetadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngestionLogRepository_CreateIngestionLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionLog'
type IngestionLogRepository_CreateIngestionLog_Call struct {
	*mock.Call
}

// CreateIngestionLog is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLog *reconcilerpb.IngestionLog
//   - sourceMetadata []byte
func (_e *IngestionLogRepository_Expecter) CreateIngestionLog(ctx interface{}, ingestionLog interface{}, sourceMetadata interface{}) *IngestionLogRepository_CreateIngestionLog_Call {
	return &IngestionLogRepository_CreateIngestionLog_Call{Call: _e.mock.On("CreateIngestionLog", ctx, ingestionLog, sourceMetadata)}
}

func (_c *IngestionLogRepository_CreateIngestionLog_Call) Run(run func(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte)) *IngestionLogRepository_CreateIngestionLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.IngestionLog), args[2].([]byte))
	})
	return _c
}

func (_c *IngestionLogRepository_CreateIngestionLog_Call) Return(_a0 error) *IngestionLogRepository_CreateIngestionLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngestionLogRepository_CreateIngestionLog_Call) RunAndReturn(run func(context.Context, *reconcilerpb.IngestionLog, []byte) error) *IngestionLogRepository_CreateIngestionLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngestionLogRepository creates a new instance of IngestionLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngestionLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngestionLogRepository {
	mock := &IngestionLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
