// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Limits is an autogenerated mock type for the Limits type
type Limits struct {
	mock.Mock
}

type Limits_Expecter struct {
	mock *mock.Mock
}

func (_m *Limits) EXPECT() *Limits_Expecter {
	return &Limits_Expecter{mock: &_m.Mock}
}

// MaxChangeSetsPerIngestionLog provides a mock function with no fields
func (_m *Limits) MaxChangeSetsPerIngestionLog() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxChangeSetsPerIngestionLog")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// Limits_MaxChangeSetsPerIngestionLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxChangeSetsPerIngestionLog'
type Limits_MaxChangeSetsPerIngestionLog_Call struct {
	*mock.Call
}

// MaxChangeSetsPerIngestionLog is a helper method to define mock.On call
func (_e *Limits_Expecter) MaxChangeSetsPerIngestionLog() *Limits_MaxChangeSetsPerIngestionLog_Call {
	return &Limits_MaxChangeSetsPerIngestionLog_Call{Call: _e.mock.On("MaxChangeSetsPerIngestionLog")}
}

func (_c *Limits_MaxChangeSetsPerIngestionLog_Call) Run(run func()) *Limits_MaxChangeSetsPerIngestionLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Limits_MaxChangeSetsPerIngestionLog_Call) Return(_a0 int32) *Limits_MaxChangeSetsPerIngestionLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Limits_MaxChangeSetsPerIngestionLog_Call) RunAndReturn(run func() int32) *Limits_MaxChangeSetsPerIngestionLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewLimits creates a new instance of Limits. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimits(t interface {
	mock.TestingT
	Cleanup(func())
}) *Limits {
	mock := &Limits{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
