// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	changeset "github.com/netboxlabs/diode/diode-server/reconciler/changeset"

	mock "github.com/stretchr/testify/mock"

	reconcilerpb "github.com/netboxlabs/diode/diode-server/gen/diode/v1/reconcilerpb"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CountIngestionLogsPerState provides a mock function with given fields: ctx
func (_m *Repository) CountIngestionLogsPerState(ctx context.Context) (map[reconcilerpb.State]int32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountIngestionLogsPerState")
	}

	var r0 map[reconcilerpb.State]int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[reconcilerpb.State]int32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[reconcilerpb.State]int32); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[reconcilerpb.State]int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CountIngestionLogsPerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountIngestionLogsPerState'
type Repository_CountIngestionLogsPerState_Call struct {
	*mock.Call
}

// CountIngestionLogsPerState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) CountIngestionLogsPerState(ctx interface{}) *Repository_CountIngestionLogsPerState_Call {
	return &Repository_CountIngestionLogsPerState_Call{Call: _e.mock.On("CountIngestionLogsPerState", ctx)}
}

func (_c *Repository_CountIngestionLogsPerState_Call) Run(run func(ctx context.Context)) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_CountIngestionLogsPerState_Call) Return(_a0 map[reconcilerpb.State]int32, _a1 error) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CountIngestionLogsPerState_Call) RunAndReturn(run func(context.Context) (map[reconcilerpb.State]int32, error)) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChangeSet provides a mock function with given fields: ctx, changeSet, ingestionLogID
func (_m *Repository) CreateChangeSet(ctx context.Context, changeSet changeset.ChangeSet, ingestionLogID int32) (*int32, error) {
	ret := _m.Called(ctx, changeSet, ingestionLogID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChangeSet")
	}

	var r0 *int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, changeset.ChangeSet, int32) (*int32, error)); ok {
		return rf(ctx, changeSet, ingestionLogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, changeset.ChangeSet, int32) *int32); ok {
		r0 = rf(ctx, changeSet, ingestionLogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, changeset.ChangeSet, int32) error); ok {
		r1 = rf(ctx, changeSet, ingestionLogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateChangeSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChangeSet'
type Repository_CreateChangeSet_Call struct {
	*mock.Call
}

// CreateChangeSet is a helper method to define mock.On call
//   - ctx context.Context
//   - changeSet changeset.ChangeSet
//   - ingestionLogID int32
func (_e *Repository_Expecter) CreateChangeSet(ctx interface{}, changeSet interface{}, ingestionLogID interface{}) *Repository_CreateChangeSet_Call {
	return &Repository_CreateChangeSet_Call{Call: _e.mock.On("CreateChangeSet", ctx, changeSet, ingestionLogID)}
}

func (_c *Repository_CreateChangeSet_Call) Run(run func(ctx context.Context, changeSet changeset.ChangeSet, ingestionLogID int32)) *Repository_CreateChangeSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(changeset.ChangeSet), args[2].(int32))
	})
	return _c
}

func (_c *Repository_CreateChangeSet_Call) Return(_a0 *int32, _a1 error) *Repository_CreateChangeSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateChangeSet_Call) RunAndReturn(run func(context.Context, changeset.ChangeSet, int32) (*int32, error)) *Repository_CreateChangeSet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIngestionLog provides a mock function with given fields: ctx, ingestionLog, sourceMetadata, entityHash
func (_m *Repository) CreateIngestionLog(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte, entityHash string) (*int32, error) {
	ret := _m.Called(ctx, ingestionLog, sourceMetadata, entityHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionLog")
	}

	var r0 *int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte, string) (*int32, error)); ok {
		return rf(ctx, ingestionLog, sourceMetadata, entityHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte, string) *int32); ok {
		r0 = rf(ctx, ingestionLog, sourceMetadata, entityHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.IngestionLog, []byte, string) error); ok {
		r1 = rf(ctx, ingestionLog, sourceMetadata, entityHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateIngestionLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionLog'
type Repository_CreateIngestionLog_Call struct {
	*mock.Call
}

// CreateIngestionLog is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLog *reconcilerpb.IngestionLog
//   - sourceMetadata []byte
//   - entityHash string
func (_e *Repository_Expecter) CreateIngestionLog(ctx interface{}, ingestionLog interface{}, sourceMetadata interface{}, entityHash interface{}) *Repository_CreateIngestionLog_Call {
	return &Repository_CreateIngestionLog_Call{Call: _e.mock.On("CreateIngestionLog", ctx, ingestionLog, sourceMetadata, entityHash)}
}

func (_c *Repository_CreateIngestionLog_Call) Run(run func(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte, entityHash string)) *Repository_CreateIngestionLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.IngestionLog), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *Repository_CreateIngestionLog_Call) Return(_a0 *int32, _a1 error) *Repository_CreateIngestionLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateIngestionLog_Call) RunAndReturn(run func(context.Context, *reconcilerpb.IngestionLog, []byte, string) (*int32, error)) *Repository_CreateIngestionLog_Call {
	_c.Call.Return(run)
	return _c
}

// FindPriorIngestionLogByEntityHash provides a mock function with given fields: ctx, entityHash, currentBranch
func (_m *Repository) FindPriorIngestionLogByEntityHash(ctx context.Context, entityHash string, currentBranch *string) (*int32, *reconcilerpb.IngestionLog, error) {
	ret := _m.Called(ctx, entityHash, currentBranch)

	if len(ret) == 0 {
		panic("no return value specified for FindPriorIngestionLogByEntityHash")
	}

	var r0 *int32
	var r1 *reconcilerpb.IngestionLog
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) (*int32, *reconcilerpb.IngestionLog, error)); ok {
		return rf(ctx, entityHash, currentBranch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) *int32); ok {
		r0 = rf(ctx, entityHash, currentBranch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) *reconcilerpb.IngestionLog); ok {
		r1 = rf(ctx, entityHash, currentBranch)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*reconcilerpb.IngestionLog)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *string) error); ok {
		r2 = rf(ctx, entityHash, currentBranch)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindPriorIngestionLogByEntityHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPriorIngestionLogByEntityHash'
type Repository_FindPriorIngestionLogByEntityHash_Call struct {
	*mock.Call
}

// FindPriorIngestionLogByEntityHash is a helper method to define mock.On call
//   - ctx context.Context
//   - entityHash string
//   - currentBranch *string
func (_e *Repository_Expecter) FindPriorIngestionLogByEntityHash(ctx interface{}, entityHash interface{}, currentBranch interface{}) *Repository_FindPriorIngestionLogByEntityHash_Call {
	return &Repository_FindPriorIngestionLogByEntityHash_Call{Call: _e.mock.On("FindPriorIngestionLogByEntityHash", ctx, entityHash, currentBranch)}
}

func (_c *Repository_FindPriorIngestionLogByEntityHash_Call) Run(run func(ctx context.Context, entityHash string, currentBranch *string)) *Repository_FindPriorIngestionLogByEntityHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *Repository_FindPriorIngestionLogByEntityHash_Call) Return(_a0 *int32, _a1 *reconcilerpb.IngestionLog, _a2 error) *Repository_FindPriorIngestionLogByEntityHash_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindPriorIngestionLogByEntityHash_Call) RunAndReturn(run func(context.Context, string, *string) (*int32, *reconcilerpb.IngestionLog, error)) *Repository_FindPriorIngestionLogByEntityHash_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementDuplicateCount provides a mock function with given fields: ctx, id
func (_m *Repository) IncrementDuplicateCount(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementDuplicateCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_IncrementDuplicateCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDuplicateCount'
type Repository_IncrementDuplicateCount_Call struct {
	*mock.Call
}

// IncrementDuplicateCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) IncrementDuplicateCount(ctx interface{}, id interface{}) *Repository_IncrementDuplicateCount_Call {
	return &Repository_IncrementDuplicateCount_Call{Call: _e.mock.On("IncrementDuplicateCount", ctx, id)}
}

func (_c *Repository_IncrementDuplicateCount_Call) Run(run func(ctx context.Context, id int32)) *Repository_IncrementDuplicateCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_IncrementDuplicateCount_Call) Return(_a0 error) *Repository_IncrementDuplicateCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_IncrementDuplicateCount_Call) RunAndReturn(run func(context.Context, int32) error) *Repository_IncrementDuplicateCount_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveDeviationByID provides a mock function with given fields: ctx, externalID
func (_m *Repository) RetrieveDeviationByID(ctx context.Context, externalID string) (*reconcilerpb.Deviation, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveDeviationByID")
	}

	var r0 *reconcilerpb.Deviation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*reconcilerpb.Deviation, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *reconcilerpb.Deviation); ok {
		r0 = rf(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reconcilerpb.Deviation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RetrieveDeviationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveDeviationByID'
type Repository_RetrieveDeviationByID_Call struct {
	*mock.Call
}

// RetrieveDeviationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *Repository_Expecter) RetrieveDeviationByID(ctx interface{}, externalID interface{}) *Repository_RetrieveDeviationByID_Call {
	return &Repository_RetrieveDeviationByID_Call{Call: _e.mock.On("RetrieveDeviationByID", ctx, externalID)}
}

func (_c *Repository_RetrieveDeviationByID_Call) Run(run func(ctx context.Context, externalID string)) *Repository_RetrieveDeviationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_RetrieveDeviationByID_Call) Return(_a0 *reconcilerpb.Deviation, _a1 error) *Repository_RetrieveDeviationByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RetrieveDeviationByID_Call) RunAndReturn(run func(context.Context, string) (*reconcilerpb.Deviation, error)) *Repository_RetrieveDeviationByID_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveDeviations provides a mock function with given fields: ctx, filter, limit, offset
func (_m *Repository) RetrieveDeviations(ctx context.Context, filter *reconcilerpb.RetrieveDeviationsRequest, limit int32, offset int32) ([]*reconcilerpb.Deviation, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveDeviations")
	}

	var r0 []*reconcilerpb.Deviation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveDeviationsRequest, int32, int32) ([]*reconcilerpb.Deviation, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveDeviationsRequest, int32, int32) []*reconcilerpb.Deviation); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reconcilerpb.Deviation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.RetrieveDeviationsRequest, int32, int32) error); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RetrieveDeviations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveDeviations'
type Repository_RetrieveDeviations_Call struct {
	*mock.Call
}

// RetrieveDeviations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *reconcilerpb.RetrieveDeviationsRequest
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) RetrieveDeviations(ctx interface{}, filter interface{}, limit interface{}, offset interface{}) *Repository_RetrieveDeviations_Call {
	return &Repository_RetrieveDeviations_Call{Call: _e.mock.On("RetrieveDeviations", ctx, filter, limit, offset)}
}

func (_c *Repository_RetrieveDeviations_Call) Run(run func(ctx context.Context, filter *reconcilerpb.RetrieveDeviationsRequest, limit int32, offset int32)) *Repository_RetrieveDeviations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.RetrieveDeviationsRequest), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_RetrieveDeviations_Call) Return(_a0 []*reconcilerpb.Deviation, _a1 error) *Repository_RetrieveDeviations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RetrieveDeviations_Call) RunAndReturn(run func(context.Context, *reconcilerpb.RetrieveDeviationsRequest, int32, int32) ([]*reconcilerpb.Deviation, error)) *Repository_RetrieveDeviations_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveIngestionLogByExternalID provides a mock function with given fields: ctx, uuid
func (_m *Repository) RetrieveIngestionLogByExternalID(ctx context.Context, uuid string) (*int32, *reconcilerpb.IngestionLog, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveIngestionLogByExternalID")
	}

	var r0 *int32
	var r1 *reconcilerpb.IngestionLog
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*int32, *reconcilerpb.IngestionLog, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *int32); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *reconcilerpb.IngestionLog); ok {
		r1 = rf(ctx, uuid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*reconcilerpb.IngestionLog)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, uuid)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_RetrieveIngestionLogByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveIngestionLogByExternalID'
type Repository_RetrieveIngestionLogByExternalID_Call struct {
	*mock.Call
}

// RetrieveIngestionLogByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *Repository_Expecter) RetrieveIngestionLogByExternalID(ctx interface{}, uuid interface{}) *Repository_RetrieveIngestionLogByExternalID_Call {
	return &Repository_RetrieveIngestionLogByExternalID_Call{Call: _e.mock.On("RetrieveIngestionLogByExternalID", ctx, uuid)}
}

func (_c *Repository_RetrieveIngestionLogByExternalID_Call) Run(run func(ctx context.Context, uuid string)) *Repository_RetrieveIngestionLogByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_RetrieveIngestionLogByExternalID_Call) Return(_a0 *int32, _a1 *reconcilerpb.IngestionLog, _a2 error) *Repository_RetrieveIngestionLogByExternalID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_RetrieveIngestionLogByExternalID_Call) RunAndReturn(run func(context.Context, string) (*int32, *reconcilerpb.IngestionLog, error)) *Repository_RetrieveIngestionLogByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveIngestionLogs provides a mock function with given fields: ctx, filter, limit, offset
func (_m *Repository) RetrieveIngestionLogs(ctx context.Context, filter *reconcilerpb.RetrieveIngestionLogsRequest, limit int32, offset int32) ([]*reconcilerpb.IngestionLog, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveIngestionLogs")
	}

	var r0 []*reconcilerpb.IngestionLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) ([]*reconcilerpb.IngestionLog, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) []*reconcilerpb.IngestionLog); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reconcilerpb.IngestionLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) error); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RetrieveIngestionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveIngestionLogs'
type Repository_RetrieveIngestionLogs_Call struct {
	*mock.Call
}

// RetrieveIngestionLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *reconcilerpb.RetrieveIngestionLogsRequest
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) RetrieveIngestionLogs(ctx interface{}, filter interface{}, limit interface{}, offset interface{}) *Repository_RetrieveIngestionLogs_Call {
	return &Repository_RetrieveIngestionLogs_Call{Call: _e.mock.On("RetrieveIngestionLogs", ctx, filter, limit, offset)}
}

func (_c *Repository_RetrieveIngestionLogs_Call) Run(run func(ctx context.Context, filter *reconcilerpb.RetrieveIngestionLogsRequest, limit int32, offset int32)) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.RetrieveIngestionLogsRequest), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_RetrieveIngestionLogs_Call) Return(_a0 []*reconcilerpb.IngestionLog, _a1 error) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RetrieveIngestionLogs_Call) RunAndReturn(run func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) ([]*reconcilerpb.IngestionLog, error)) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Return(run)
	return _c
}

// TruncateChangeSets provides a mock function with given fields: ctx, ingestionLogID, limit
func (_m *Repository) TruncateChangeSets(ctx context.Context, ingestionLogID int32, limit int32) error {
	ret := _m.Called(ctx, ingestionLogID, limit)

	if len(ret) == 0 {
		panic("no return value specified for TruncateChangeSets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) error); ok {
		r0 = rf(ctx, ingestionLogID, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_TruncateChangeSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TruncateChangeSets'
type Repository_TruncateChangeSets_Call struct {
	*mock.Call
}

// TruncateChangeSets is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLogID int32
//   - limit int32
func (_e *Repository_Expecter) TruncateChangeSets(ctx interface{}, ingestionLogID interface{}, limit interface{}) *Repository_TruncateChangeSets_Call {
	return &Repository_TruncateChangeSets_Call{Call: _e.mock.On("TruncateChangeSets", ctx, ingestionLogID, limit)}
}

func (_c *Repository_TruncateChangeSets_Call) Run(run func(ctx context.Context, ingestionLogID int32, limit int32)) *Repository_TruncateChangeSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *Repository_TruncateChangeSets_Call) Return(_a0 error) *Repository_TruncateChangeSets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_TruncateChangeSets_Call) RunAndReturn(run func(context.Context, int32, int32) error) *Repository_TruncateChangeSets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngestionLogStateWithError provides a mock function with given fields: ctx, id, state, err
func (_m *Repository) UpdateIngestionLogStateWithError(ctx context.Context, id int32, state reconcilerpb.State, err error) error {
	ret := _m.Called(ctx, id, state, err)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngestionLogStateWithError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, reconcilerpb.State, error) error); ok {
		r0 = rf(ctx, id, state, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateIngestionLogStateWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngestionLogStateWithError'
type Repository_UpdateIngestionLogStateWithError_Call struct {
	*mock.Call
}

// UpdateIngestionLogStateWithError is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - state reconcilerpb.State
//   - err error
func (_e *Repository_Expecter) UpdateIngestionLogStateWithError(ctx interface{}, id interface{}, state interface{}, err interface{}) *Repository_UpdateIngestionLogStateWithError_Call {
	return &Repository_UpdateIngestionLogStateWithError_Call{Call: _e.mock.On("UpdateIngestionLogStateWithError", ctx, id, state, err)}
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) Run(run func(ctx context.Context, id int32, state reconcilerpb.State, err error)) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(reconcilerpb.State), args[3].(error))
	})
	return _c
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) Return(_a0 error) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) RunAndReturn(run func(context.Context, int32, reconcilerpb.State, error) error) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
