// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	changeset "github.com/netboxlabs/diode/diode-server/reconciler/changeset"

	mock "github.com/stretchr/testify/mock"

	reconcilerpb "github.com/netboxlabs/diode/diode-server/gen/diode/v1/reconcilerpb"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CountIngestionLogsPerState provides a mock function with given fields: ctx
func (_m *Repository) CountIngestionLogsPerState(ctx context.Context) (map[reconcilerpb.State]int32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountIngestionLogsPerState")
	}

	var r0 map[reconcilerpb.State]int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[reconcilerpb.State]int32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[reconcilerpb.State]int32); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[reconcilerpb.State]int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CountIngestionLogsPerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountIngestionLogsPerState'
type Repository_CountIngestionLogsPerState_Call struct {
	*mock.Call
}

// CountIngestionLogsPerState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) CountIngestionLogsPerState(ctx interface{}) *Repository_CountIngestionLogsPerState_Call {
	return &Repository_CountIngestionLogsPerState_Call{Call: _e.mock.On("CountIngestionLogsPerState", ctx)}
}

func (_c *Repository_CountIngestionLogsPerState_Call) Run(run func(ctx context.Context)) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Repository_CountIngestionLogsPerState_Call) Return(_a0 map[reconcilerpb.State]int32, _a1 error) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CountIngestionLogsPerState_Call) RunAndReturn(run func(context.Context) (map[reconcilerpb.State]int32, error)) *Repository_CountIngestionLogsPerState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChangeSet provides a mock function with given fields: ctx, changeSet, ingestionLogID
func (_m *Repository) CreateChangeSet(ctx context.Context, changeSet changeset.ChangeSet, ingestionLogID int32) (*int32, error) {
	ret := _m.Called(ctx, changeSet, ingestionLogID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChangeSet")
	}

	var r0 *int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, changeset.ChangeSet, int32) (*int32, error)); ok {
		return rf(ctx, changeSet, ingestionLogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, changeset.ChangeSet, int32) *int32); ok {
		r0 = rf(ctx, changeSet, ingestionLogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, changeset.ChangeSet, int32) error); ok {
		r1 = rf(ctx, changeSet, ingestionLogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateChangeSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChangeSet'
type Repository_CreateChangeSet_Call struct {
	*mock.Call
}

// CreateChangeSet is a helper method to define mock.On call
//   - ctx context.Context
//   - changeSet changeset.ChangeSet
//   - ingestionLogID int32
func (_e *Repository_Expecter) CreateChangeSet(ctx interface{}, changeSet interface{}, ingestionLogID interface{}) *Repository_CreateChangeSet_Call {
	return &Repository_CreateChangeSet_Call{Call: _e.mock.On("CreateChangeSet", ctx, changeSet, ingestionLogID)}
}

func (_c *Repository_CreateChangeSet_Call) Run(run func(ctx context.Context, changeSet changeset.ChangeSet, ingestionLogID int32)) *Repository_CreateChangeSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(changeset.ChangeSet), args[2].(int32))
	})
	return _c
}

func (_c *Repository_CreateChangeSet_Call) Return(_a0 *int32, _a1 error) *Repository_CreateChangeSet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateChangeSet_Call) RunAndReturn(run func(context.Context, changeset.ChangeSet, int32) (*int32, error)) *Repository_CreateChangeSet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIngestionLog provides a mock function with given fields: ctx, ingestionLog, sourceMetadata
func (_m *Repository) CreateIngestionLog(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte) (*int32, error) {
	ret := _m.Called(ctx, ingestionLog, sourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionLog")
	}

	var r0 *int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte) (*int32, error)); ok {
		return rf(ctx, ingestionLog, sourceMetadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.IngestionLog, []byte) *int32); ok {
		r0 = rf(ctx, ingestionLog, sourceMetadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.IngestionLog, []byte) error); ok {
		r1 = rf(ctx, ingestionLog, sourceMetadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateIngestionLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionLog'
type Repository_CreateIngestionLog_Call struct {
	*mock.Call
}

// CreateIngestionLog is a helper method to define mock.On call
//   - ctx context.Context
//   - ingestionLog *reconcilerpb.IngestionLog
//   - sourceMetadata []byte
func (_e *Repository_Expecter) CreateIngestionLog(ctx interface{}, ingestionLog interface{}, sourceMetadata interface{}) *Repository_CreateIngestionLog_Call {
	return &Repository_CreateIngestionLog_Call{Call: _e.mock.On("CreateIngestionLog", ctx, ingestionLog, sourceMetadata)}
}

func (_c *Repository_CreateIngestionLog_Call) Run(run func(ctx context.Context, ingestionLog *reconcilerpb.IngestionLog, sourceMetadata []byte)) *Repository_CreateIngestionLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.IngestionLog), args[2].([]byte))
	})
	return _c
}

func (_c *Repository_CreateIngestionLog_Call) Return(_a0 *int32, _a1 error) *Repository_CreateIngestionLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateIngestionLog_Call) RunAndReturn(run func(context.Context, *reconcilerpb.IngestionLog, []byte) (*int32, error)) *Repository_CreateIngestionLog_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveIngestionLogs provides a mock function with given fields: ctx, filter, limit, offset
func (_m *Repository) RetrieveIngestionLogs(ctx context.Context, filter *reconcilerpb.RetrieveIngestionLogsRequest, limit int32, offset int32) ([]*reconcilerpb.IngestionLog, error) {
	ret := _m.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveIngestionLogs")
	}

	var r0 []*reconcilerpb.IngestionLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) ([]*reconcilerpb.IngestionLog, error)); ok {
		return rf(ctx, filter, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) []*reconcilerpb.IngestionLog); ok {
		r0 = rf(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reconcilerpb.IngestionLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) error); ok {
		r1 = rf(ctx, filter, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RetrieveIngestionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveIngestionLogs'
type Repository_RetrieveIngestionLogs_Call struct {
	*mock.Call
}

// RetrieveIngestionLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *reconcilerpb.RetrieveIngestionLogsRequest
//   - limit int32
//   - offset int32
func (_e *Repository_Expecter) RetrieveIngestionLogs(ctx interface{}, filter interface{}, limit interface{}, offset interface{}) *Repository_RetrieveIngestionLogs_Call {
	return &Repository_RetrieveIngestionLogs_Call{Call: _e.mock.On("RetrieveIngestionLogs", ctx, filter, limit, offset)}
}

func (_c *Repository_RetrieveIngestionLogs_Call) Run(run func(ctx context.Context, filter *reconcilerpb.RetrieveIngestionLogsRequest, limit int32, offset int32)) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reconcilerpb.RetrieveIngestionLogsRequest), args[2].(int32), args[3].(int32))
	})
	return _c
}

func (_c *Repository_RetrieveIngestionLogs_Call) Return(_a0 []*reconcilerpb.IngestionLog, _a1 error) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RetrieveIngestionLogs_Call) RunAndReturn(run func(context.Context, *reconcilerpb.RetrieveIngestionLogsRequest, int32, int32) ([]*reconcilerpb.IngestionLog, error)) *Repository_RetrieveIngestionLogs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngestionLogStateWithError provides a mock function with given fields: ctx, id, state, ingestionError
func (_m *Repository) UpdateIngestionLogStateWithError(ctx context.Context, id int32, state reconcilerpb.State, ingestionError *reconcilerpb.IngestionError) error {
	ret := _m.Called(ctx, id, state, ingestionError)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngestionLogStateWithError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, reconcilerpb.State, *reconcilerpb.IngestionError) error); ok {
		r0 = rf(ctx, id, state, ingestionError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateIngestionLogStateWithError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngestionLogStateWithError'
type Repository_UpdateIngestionLogStateWithError_Call struct {
	*mock.Call
}

// UpdateIngestionLogStateWithError is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - state reconcilerpb.State
//   - ingestionError *reconcilerpb.IngestionError
func (_e *Repository_Expecter) UpdateIngestionLogStateWithError(ctx interface{}, id interface{}, state interface{}, ingestionError interface{}) *Repository_UpdateIngestionLogStateWithError_Call {
	return &Repository_UpdateIngestionLogStateWithError_Call{Call: _e.mock.On("UpdateIngestionLogStateWithError", ctx, id, state, ingestionError)}
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) Run(run func(ctx context.Context, id int32, state reconcilerpb.State, ingestionError *reconcilerpb.IngestionError)) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(reconcilerpb.State), args[3].(*reconcilerpb.IngestionError))
	})
	return _c
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) Return(_a0 error) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateIngestionLogStateWithError_Call) RunAndReturn(run func(context.Context, int32, reconcilerpb.State, *reconcilerpb.IngestionError) error) *Repository_UpdateIngestionLogStateWithError_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
