// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// EdgeWriter is an autogenerated mock type for the EdgeWriter type
type EdgeWriter struct {
	mock.Mock
}

type EdgeWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *EdgeWriter) EXPECT() *EdgeWriter_Expecter {
	return &EdgeWriter_Expecter{mock: &_m.Mock}
}

// UpsertEdge provides a mock function with given fields: ctx, arg
func (_m *EdgeWriter) UpsertEdge(ctx context.Context, arg graph.UpsertEdgeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEdge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertEdgeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EdgeWriter_UpsertEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEdge'
type EdgeWriter_UpsertEdge_Call struct {
	*mock.Call
}

// UpsertEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpsertEdgeParams
func (_e *EdgeWriter_Expecter) UpsertEdge(ctx interface{}, arg interface{}) *EdgeWriter_UpsertEdge_Call {
	return &EdgeWriter_UpsertEdge_Call{Call: _e.mock.On("UpsertEdge", ctx, arg)}
}

func (_c *EdgeWriter_UpsertEdge_Call) Run(run func(ctx context.Context, arg graph.UpsertEdgeParams)) *EdgeWriter_UpsertEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpsertEdgeParams))
	})
	return _c
}

func (_c *EdgeWriter_UpsertEdge_Call) Return(_a0 error) *EdgeWriter_UpsertEdge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EdgeWriter_UpsertEdge_Call) RunAndReturn(run func(context.Context, graph.UpsertEdgeParams) error) *EdgeWriter_UpsertEdge_Call {
	_c.Call.Return(run)
	return _c
}

// NewEdgeWriter creates a new instance of EdgeWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEdgeWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EdgeWriter {
	mock := &EdgeWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
