// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	diodepb "github.com/netboxlabs/diode/diode-server/gen/diode/v1/diodepb"
	graph "github.com/netboxlabs/diode/diode-server/graph"

	mock "github.com/stretchr/testify/mock"
)

// EntityStore is an autogenerated mock type for the EntityStore type
type EntityStore struct {
	mock.Mock
}

type EntityStore_Expecter struct {
	mock *mock.Mock
}

func (_m *EntityStore) EXPECT() *EntityStore_Expecter {
	return &EntityStore_Expecter{mock: &_m.Mock}
}

// ListEntities provides a mock function with given fields: ctx, params
func (_m *EntityStore) ListEntities(ctx context.Context, params graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListEntities")
	}

	var r0 []graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) []graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.NodeWithLatestSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.ListNodesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EntityStore_ListEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEntities'
type EntityStore_ListEntities_Call struct {
	*mock.Call
}

// ListEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - params graph.ListNodesParams
func (_e *EntityStore_Expecter) ListEntities(ctx interface{}, params interface{}) *EntityStore_ListEntities_Call {
	return &EntityStore_ListEntities_Call{Call: _e.mock.On("ListEntities", ctx, params)}
}

func (_c *EntityStore_ListEntities_Call) Run(run func(ctx context.Context, params graph.ListNodesParams)) *EntityStore_ListEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.ListNodesParams))
	})
	return _c
}

func (_c *EntityStore_ListEntities_Call) Return(_a0 []graph.NodeWithLatestSnapshot, _a1 error) *EntityStore_ListEntities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EntityStore_ListEntities_Call) RunAndReturn(run func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)) *EntityStore_ListEntities_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEntity provides a mock function with given fields: ctx, entity
func (_m *EntityStore) UpsertEntity(ctx context.Context, entity *diodepb.Entity) (*graph.Node, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEntity")
	}

	var r0 *graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *diodepb.Entity) (*graph.Node, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *diodepb.Entity) *graph.Node); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *diodepb.Entity) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EntityStore_UpsertEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEntity'
type EntityStore_UpsertEntity_Call struct {
	*mock.Call
}

// UpsertEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *diodepb.Entity
func (_e *EntityStore_Expecter) UpsertEntity(ctx interface{}, entity interface{}) *EntityStore_UpsertEntity_Call {
	return &EntityStore_UpsertEntity_Call{Call: _e.mock.On("UpsertEntity", ctx, entity)}
}

func (_c *EntityStore_UpsertEntity_Call) Run(run func(ctx context.Context, entity *diodepb.Entity)) *EntityStore_UpsertEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*diodepb.Entity))
	})
	return _c
}

func (_c *EntityStore_UpsertEntity_Call) Return(_a0 *graph.Node, _a1 error) *EntityStore_UpsertEntity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EntityStore_UpsertEntity_Call) RunAndReturn(run func(context.Context, *diodepb.Entity) (*graph.Node, error)) *EntityStore_UpsertEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewEntityStore creates a new instance of EntityStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityStore {
	mock := &EntityStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
