// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// NodeReader is an autogenerated mock type for the NodeReader type
type NodeReader struct {
	mock.Mock
}

type NodeReader_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeReader) EXPECT() *NodeReader_Expecter {
	return &NodeReader_Expecter{mock: &_m.Mock}
}

// FindNode provides a mock function with given fields: ctx, arg
func (_m *NodeReader) FindNode(ctx context.Context, arg graph.FindNodeParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNode")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_FindNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNode'
type NodeReader_FindNode_Call struct {
	*mock.Call
}

// FindNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeParams
func (_e *NodeReader_Expecter) FindNode(ctx interface{}, arg interface{}) *NodeReader_FindNode_Call {
	return &NodeReader_FindNode_Call{Call: _e.mock.On("FindNode", ctx, arg)}
}

func (_c *NodeReader_FindNode_Call) Run(run func(ctx context.Context, arg graph.FindNodeParams)) *NodeReader_FindNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeParams))
	})
	return _c
}

func (_c *NodeReader_FindNode_Call) Return(_a0 graph.Node, _a1 error) *NodeReader_FindNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_FindNode_Call) RunAndReturn(run func(context.Context, graph.FindNodeParams) (graph.Node, error)) *NodeReader_FindNode_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodeByContentHash provides a mock function with given fields: ctx, arg
func (_m *NodeReader) FindNodeByContentHash(ctx context.Context, arg graph.FindNodeByContentHashParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByContentHash")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByContentHashParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByContentHashParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeByContentHashParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_FindNodeByContentHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByContentHash'
type NodeReader_FindNodeByContentHash_Call struct {
	*mock.Call
}

// FindNodeByContentHash is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeByContentHashParams
func (_e *NodeReader_Expecter) FindNodeByContentHash(ctx interface{}, arg interface{}) *NodeReader_FindNodeByContentHash_Call {
	return &NodeReader_FindNodeByContentHash_Call{Call: _e.mock.On("FindNodeByContentHash", ctx, arg)}
}

func (_c *NodeReader_FindNodeByContentHash_Call) Run(run func(ctx context.Context, arg graph.FindNodeByContentHashParams)) *NodeReader_FindNodeByContentHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeByContentHashParams))
	})
	return _c
}

func (_c *NodeReader_FindNodeByContentHash_Call) Return(_a0 graph.Node, _a1 error) *NodeReader_FindNodeByContentHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_FindNodeByContentHash_Call) RunAndReturn(run func(context.Context, graph.FindNodeByContentHashParams) (graph.Node, error)) *NodeReader_FindNodeByContentHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodeByMetadata provides a mock function with given fields: ctx, arg
func (_m *NodeReader) FindNodeByMetadata(ctx context.Context, arg graph.FindNodeByMetadataParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByMetadata")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeByMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_FindNodeByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByMetadata'
type NodeReader_FindNodeByMetadata_Call struct {
	*mock.Call
}

// FindNodeByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeByMetadataParams
func (_e *NodeReader_Expecter) FindNodeByMetadata(ctx interface{}, arg interface{}) *NodeReader_FindNodeByMetadata_Call {
	return &NodeReader_FindNodeByMetadata_Call{Call: _e.mock.On("FindNodeByMetadata", ctx, arg)}
}

func (_c *NodeReader_FindNodeByMetadata_Call) Run(run func(ctx context.Context, arg graph.FindNodeByMetadataParams)) *NodeReader_FindNodeByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeByMetadataParams))
	})
	return _c
}

func (_c *NodeReader_FindNodeByMetadata_Call) Return(_a0 graph.Node, _a1 error) *NodeReader_FindNodeByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_FindNodeByMetadata_Call) RunAndReturn(run func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)) *NodeReader_FindNodeByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodesByFieldMatch provides a mock function with given fields: ctx, arg
func (_m *NodeReader) FindNodesByFieldMatch(ctx context.Context, arg graph.FindNodesByFieldMatchParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodesByFieldMatch")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodesByFieldMatchParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_FindNodesByFieldMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodesByFieldMatch'
type NodeReader_FindNodesByFieldMatch_Call struct {
	*mock.Call
}

// FindNodesByFieldMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodesByFieldMatchParams
func (_e *NodeReader_Expecter) FindNodesByFieldMatch(ctx interface{}, arg interface{}) *NodeReader_FindNodesByFieldMatch_Call {
	return &NodeReader_FindNodesByFieldMatch_Call{Call: _e.mock.On("FindNodesByFieldMatch", ctx, arg)}
}

func (_c *NodeReader_FindNodesByFieldMatch_Call) Run(run func(ctx context.Context, arg graph.FindNodesByFieldMatchParams)) *NodeReader_FindNodesByFieldMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodesByFieldMatchParams))
	})
	return _c
}

func (_c *NodeReader_FindNodesByFieldMatch_Call) Return(_a0 []graph.Node, _a1 error) *NodeReader_FindNodesByFieldMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_FindNodesByFieldMatch_Call) RunAndReturn(run func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)) *NodeReader_FindNodesByFieldMatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodesByType provides a mock function with given fields: ctx, arg
func (_m *NodeReader) GetNodesByType(ctx context.Context, arg graph.GetNodesByTypeParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetNodesByType")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetNodesByTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_GetNodesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodesByType'
type NodeReader_GetNodesByType_Call struct {
	*mock.Call
}

// GetNodesByType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetNodesByTypeParams
func (_e *NodeReader_Expecter) GetNodesByType(ctx interface{}, arg interface{}) *NodeReader_GetNodesByType_Call {
	return &NodeReader_GetNodesByType_Call{Call: _e.mock.On("GetNodesByType", ctx, arg)}
}

func (_c *NodeReader_GetNodesByType_Call) Run(run func(ctx context.Context, arg graph.GetNodesByTypeParams)) *NodeReader_GetNodesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetNodesByTypeParams))
	})
	return _c
}

func (_c *NodeReader_GetNodesByType_Call) Return(_a0 []graph.Node, _a1 error) *NodeReader_GetNodesByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_GetNodesByType_Call) RunAndReturn(run func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)) *NodeReader_GetNodesByType_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodes provides a mock function with given fields: ctx, arg
func (_m *NodeReader) ListNodes(ctx context.Context, arg graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) []graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.NodeWithLatestSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.ListNodesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeReader_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type NodeReader_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.ListNodesParams
func (_e *NodeReader_Expecter) ListNodes(ctx interface{}, arg interface{}) *NodeReader_ListNodes_Call {
	return &NodeReader_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx, arg)}
}

func (_c *NodeReader_ListNodes_Call) Run(run func(ctx context.Context, arg graph.ListNodesParams)) *NodeReader_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.ListNodesParams))
	})
	return _c
}

func (_c *NodeReader_ListNodes_Call) Return(_a0 []graph.NodeWithLatestSnapshot, _a1 error) *NodeReader_ListNodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeReader_ListNodes_Call) RunAndReturn(run func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)) *NodeReader_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// NewNodeReader creates a new instance of NodeReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeReader {
	mock := &NodeReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
