// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// NodeWriter is an autogenerated mock type for the NodeWriter type
type NodeWriter struct {
	mock.Mock
}

type NodeWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeWriter) EXPECT() *NodeWriter_Expecter {
	return &NodeWriter_Expecter{mock: &_m.Mock}
}

// UpdateNodeData provides a mock function with given fields: ctx, arg
func (_m *NodeWriter) UpdateNodeData(ctx context.Context, arg graph.UpdateNodeDataParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeData")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpdateNodeDataParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpdateNodeDataParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.UpdateNodeDataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeWriter_UpdateNodeData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNodeData'
type NodeWriter_UpdateNodeData_Call struct {
	*mock.Call
}

// UpdateNodeData is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpdateNodeDataParams
func (_e *NodeWriter_Expecter) UpdateNodeData(ctx interface{}, arg interface{}) *NodeWriter_UpdateNodeData_Call {
	return &NodeWriter_UpdateNodeData_Call{Call: _e.mock.On("UpdateNodeData", ctx, arg)}
}

func (_c *NodeWriter_UpdateNodeData_Call) Run(run func(ctx context.Context, arg graph.UpdateNodeDataParams)) *NodeWriter_UpdateNodeData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpdateNodeDataParams))
	})
	return _c
}

func (_c *NodeWriter_UpdateNodeData_Call) Return(_a0 graph.Node, _a1 error) *NodeWriter_UpdateNodeData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeWriter_UpdateNodeData_Call) RunAndReturn(run func(context.Context, graph.UpdateNodeDataParams) (graph.Node, error)) *NodeWriter_UpdateNodeData_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNode provides a mock function with given fields: ctx, arg
func (_m *NodeWriter) UpsertNode(ctx context.Context, arg graph.UpsertNodeParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNode")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertNodeParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertNodeParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.UpsertNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeWriter_UpsertNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNode'
type NodeWriter_UpsertNode_Call struct {
	*mock.Call
}

// UpsertNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpsertNodeParams
func (_e *NodeWriter_Expecter) UpsertNode(ctx interface{}, arg interface{}) *NodeWriter_UpsertNode_Call {
	return &NodeWriter_UpsertNode_Call{Call: _e.mock.On("UpsertNode", ctx, arg)}
}

func (_c *NodeWriter_UpsertNode_Call) Run(run func(ctx context.Context, arg graph.UpsertNodeParams)) *NodeWriter_UpsertNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpsertNodeParams))
	})
	return _c
}

func (_c *NodeWriter_UpsertNode_Call) Return(_a0 graph.Node, _a1 error) *NodeWriter_UpsertNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeWriter_UpsertNode_Call) RunAndReturn(run func(context.Context, graph.UpsertNodeParams) (graph.Node, error)) *NodeWriter_UpsertNode_Call {
	_c.Call.Return(run)
	return _c
}

// NewNodeWriter creates a new instance of NodeWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeWriter {
	mock := &NodeWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
