// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CleanupExpiredSnapshots provides a mock function with given fields: ctx, arg
func (_m *Repository) CleanupExpiredSnapshots(ctx context.Context, arg graph.CleanupExpiredSnapshotsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredSnapshots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.CleanupExpiredSnapshotsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CleanupExpiredSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpiredSnapshots'
type Repository_CleanupExpiredSnapshots_Call struct {
	*mock.Call
}

// CleanupExpiredSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.CleanupExpiredSnapshotsParams
func (_e *Repository_Expecter) CleanupExpiredSnapshots(ctx interface{}, arg interface{}) *Repository_CleanupExpiredSnapshots_Call {
	return &Repository_CleanupExpiredSnapshots_Call{Call: _e.mock.On("CleanupExpiredSnapshots", ctx, arg)}
}

func (_c *Repository_CleanupExpiredSnapshots_Call) Run(run func(ctx context.Context, arg graph.CleanupExpiredSnapshotsParams)) *Repository_CleanupExpiredSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.CleanupExpiredSnapshotsParams))
	})
	return _c
}

func (_c *Repository_CleanupExpiredSnapshots_Call) Return(_a0 error) *Repository_CleanupExpiredSnapshots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CleanupExpiredSnapshots_Call) RunAndReturn(run func(context.Context, graph.CleanupExpiredSnapshotsParams) error) *Repository_CleanupExpiredSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// CleanupOldSnapshots provides a mock function with given fields: ctx, arg
func (_m *Repository) CleanupOldSnapshots(ctx context.Context, arg graph.CleanupOldSnapshotsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldSnapshots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.CleanupOldSnapshotsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CleanupOldSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldSnapshots'
type Repository_CleanupOldSnapshots_Call struct {
	*mock.Call
}

// CleanupOldSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.CleanupOldSnapshotsParams
func (_e *Repository_Expecter) CleanupOldSnapshots(ctx interface{}, arg interface{}) *Repository_CleanupOldSnapshots_Call {
	return &Repository_CleanupOldSnapshots_Call{Call: _e.mock.On("CleanupOldSnapshots", ctx, arg)}
}

func (_c *Repository_CleanupOldSnapshots_Call) Run(run func(ctx context.Context, arg graph.CleanupOldSnapshotsParams)) *Repository_CleanupOldSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.CleanupOldSnapshotsParams))
	})
	return _c
}

func (_c *Repository_CleanupOldSnapshots_Call) Return(_a0 error) *Repository_CleanupOldSnapshots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CleanupOldSnapshots_Call) RunAndReturn(run func(context.Context, graph.CleanupOldSnapshotsParams) error) *Repository_CleanupOldSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// FindLatestSnapshotByHash provides a mock function with given fields: ctx, arg
func (_m *Repository) FindLatestSnapshotByHash(ctx context.Context, arg graph.FindLatestSnapshotByHashParams) (graph.Snapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindLatestSnapshotByHash")
	}

	var r0 graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindLatestSnapshotByHashParams) (graph.Snapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindLatestSnapshotByHashParams) graph.Snapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindLatestSnapshotByHashParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindLatestSnapshotByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLatestSnapshotByHash'
type Repository_FindLatestSnapshotByHash_Call struct {
	*mock.Call
}

// FindLatestSnapshotByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindLatestSnapshotByHashParams
func (_e *Repository_Expecter) FindLatestSnapshotByHash(ctx interface{}, arg interface{}) *Repository_FindLatestSnapshotByHash_Call {
	return &Repository_FindLatestSnapshotByHash_Call{Call: _e.mock.On("FindLatestSnapshotByHash", ctx, arg)}
}

func (_c *Repository_FindLatestSnapshotByHash_Call) Run(run func(ctx context.Context, arg graph.FindLatestSnapshotByHashParams)) *Repository_FindLatestSnapshotByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindLatestSnapshotByHashParams))
	})
	return _c
}

func (_c *Repository_FindLatestSnapshotByHash_Call) Return(_a0 graph.Snapshot, _a1 error) *Repository_FindLatestSnapshotByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindLatestSnapshotByHash_Call) RunAndReturn(run func(context.Context, graph.FindLatestSnapshotByHashParams) (graph.Snapshot, error)) *Repository_FindLatestSnapshotByHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindNode provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNode(ctx context.Context, arg graph.FindNodeParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNode")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNode'
type Repository_FindNode_Call struct {
	*mock.Call
}

// FindNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeParams
func (_e *Repository_Expecter) FindNode(ctx interface{}, arg interface{}) *Repository_FindNode_Call {
	return &Repository_FindNode_Call{Call: _e.mock.On("FindNode", ctx, arg)}
}

func (_c *Repository_FindNode_Call) Run(run func(ctx context.Context, arg graph.FindNodeParams)) *Repository_FindNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeParams))
	})
	return _c
}

func (_c *Repository_FindNode_Call) Return(_a0 graph.Node, _a1 error) *Repository_FindNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNode_Call) RunAndReturn(run func(context.Context, graph.FindNodeParams) (graph.Node, error)) *Repository_FindNode_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodeByContentHash provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNodeByContentHash(ctx context.Context, arg graph.FindNodeByContentHashParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByContentHash")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByContentHashParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByContentHashParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeByContentHashParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNodeByContentHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByContentHash'
type Repository_FindNodeByContentHash_Call struct {
	*mock.Call
}

// FindNodeByContentHash is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeByContentHashParams
func (_e *Repository_Expecter) FindNodeByContentHash(ctx interface{}, arg interface{}) *Repository_FindNodeByContentHash_Call {
	return &Repository_FindNodeByContentHash_Call{Call: _e.mock.On("FindNodeByContentHash", ctx, arg)}
}

func (_c *Repository_FindNodeByContentHash_Call) Run(run func(ctx context.Context, arg graph.FindNodeByContentHashParams)) *Repository_FindNodeByContentHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeByContentHashParams))
	})
	return _c
}

func (_c *Repository_FindNodeByContentHash_Call) Return(_a0 graph.Node, _a1 error) *Repository_FindNodeByContentHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNodeByContentHash_Call) RunAndReturn(run func(context.Context, graph.FindNodeByContentHashParams) (graph.Node, error)) *Repository_FindNodeByContentHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodeByMetadata provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNodeByMetadata(ctx context.Context, arg graph.FindNodeByMetadataParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByMetadata")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeByMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNodeByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByMetadata'
type Repository_FindNodeByMetadata_Call struct {
	*mock.Call
}

// FindNodeByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeByMetadataParams
func (_e *Repository_Expecter) FindNodeByMetadata(ctx interface{}, arg interface{}) *Repository_FindNodeByMetadata_Call {
	return &Repository_FindNodeByMetadata_Call{Call: _e.mock.On("FindNodeByMetadata", ctx, arg)}
}

func (_c *Repository_FindNodeByMetadata_Call) Run(run func(ctx context.Context, arg graph.FindNodeByMetadataParams)) *Repository_FindNodeByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeByMetadataParams))
	})
	return _c
}

func (_c *Repository_FindNodeByMetadata_Call) Return(_a0 graph.Node, _a1 error) *Repository_FindNodeByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNodeByMetadata_Call) RunAndReturn(run func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)) *Repository_FindNodeByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodesByFieldMatch provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNodesByFieldMatch(ctx context.Context, arg graph.FindNodesByFieldMatchParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodesByFieldMatch")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodesByFieldMatchParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNodesByFieldMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodesByFieldMatch'
type Repository_FindNodesByFieldMatch_Call struct {
	*mock.Call
}

// FindNodesByFieldMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodesByFieldMatchParams
func (_e *Repository_Expecter) FindNodesByFieldMatch(ctx interface{}, arg interface{}) *Repository_FindNodesByFieldMatch_Call {
	return &Repository_FindNodesByFieldMatch_Call{Call: _e.mock.On("FindNodesByFieldMatch", ctx, arg)}
}

func (_c *Repository_FindNodesByFieldMatch_Call) Run(run func(ctx context.Context, arg graph.FindNodesByFieldMatchParams)) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodesByFieldMatchParams))
	})
	return _c
}

func (_c *Repository_FindNodesByFieldMatch_Call) Return(_a0 []graph.Node, _a1 error) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNodesByFieldMatch_Call) RunAndReturn(run func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSnapshot provides a mock function with given fields: ctx, nodeID
func (_m *Repository) GetLatestSnapshot(ctx context.Context, nodeID int64) (graph.Snapshot, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSnapshot")
	}

	var r0 graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (graph.Snapshot, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) graph.Snapshot); ok {
		r0 = rf(ctx, nodeID)
	} else {
		r0 = ret.Get(0).(graph.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetLatestSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSnapshot'
type Repository_GetLatestSnapshot_Call struct {
	*mock.Call
}

// GetLatestSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *Repository_Expecter) GetLatestSnapshot(ctx interface{}, nodeID interface{}) *Repository_GetLatestSnapshot_Call {
	return &Repository_GetLatestSnapshot_Call{Call: _e.mock.On("GetLatestSnapshot", ctx, nodeID)}
}

func (_c *Repository_GetLatestSnapshot_Call) Run(run func(ctx context.Context, nodeID int64)) *Repository_GetLatestSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Repository_GetLatestSnapshot_Call) Return(_a0 graph.Snapshot, _a1 error) *Repository_GetLatestSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetLatestSnapshot_Call) RunAndReturn(run func(context.Context, int64) (graph.Snapshot, error)) *Repository_GetLatestSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeWithLatestSnapshot provides a mock function with given fields: ctx, arg
func (_m *Repository) GetNodeWithLatestSnapshot(ctx context.Context, arg graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeWithLatestSnapshot")
	}

	var r0 graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.NodeWithLatestSnapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetNodeWithLatestSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeWithLatestSnapshot'
type Repository_GetNodeWithLatestSnapshot_Call struct {
	*mock.Call
}

// GetNodeWithLatestSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetNodeWithLatestSnapshotParams
func (_e *Repository_Expecter) GetNodeWithLatestSnapshot(ctx interface{}, arg interface{}) *Repository_GetNodeWithLatestSnapshot_Call {
	return &Repository_GetNodeWithLatestSnapshot_Call{Call: _e.mock.On("GetNodeWithLatestSnapshot", ctx, arg)}
}

func (_c *Repository_GetNodeWithLatestSnapshot_Call) Run(run func(ctx context.Context, arg graph.GetNodeWithLatestSnapshotParams)) *Repository_GetNodeWithLatestSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetNodeWithLatestSnapshotParams))
	})
	return _c
}

func (_c *Repository_GetNodeWithLatestSnapshot_Call) Return(_a0 graph.NodeWithLatestSnapshot, _a1 error) *Repository_GetNodeWithLatestSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetNodeWithLatestSnapshot_Call) RunAndReturn(run func(context.Context, graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error)) *Repository_GetNodeWithLatestSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodesByType provides a mock function with given fields: ctx, arg
func (_m *Repository) GetNodesByType(ctx context.Context, arg graph.GetNodesByTypeParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetNodesByType")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetNodesByTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetNodesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodesByType'
type Repository_GetNodesByType_Call struct {
	*mock.Call
}

// GetNodesByType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetNodesByTypeParams
func (_e *Repository_Expecter) GetNodesByType(ctx interface{}, arg interface{}) *Repository_GetNodesByType_Call {
	return &Repository_GetNodesByType_Call{Call: _e.mock.On("GetNodesByType", ctx, arg)}
}

func (_c *Repository_GetNodesByType_Call) Run(run func(ctx context.Context, arg graph.GetNodesByTypeParams)) *Repository_GetNodesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetNodesByTypeParams))
	})
	return _c
}

func (_c *Repository_GetNodesByType_Call) Return(_a0 []graph.Node, _a1 error) *Repository_GetNodesByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetNodesByType_Call) RunAndReturn(run func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)) *Repository_GetNodesByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshotsByNode provides a mock function with given fields: ctx, arg
func (_m *Repository) GetSnapshotsByNode(ctx context.Context, arg graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshotsByNode")
	}

	var r0 []graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetSnapshotsByNodeParams) []graph.Snapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetSnapshotsByNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetSnapshotsByNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshotsByNode'
type Repository_GetSnapshotsByNode_Call struct {
	*mock.Call
}

// GetSnapshotsByNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetSnapshotsByNodeParams
func (_e *Repository_Expecter) GetSnapshotsByNode(ctx interface{}, arg interface{}) *Repository_GetSnapshotsByNode_Call {
	return &Repository_GetSnapshotsByNode_Call{Call: _e.mock.On("GetSnapshotsByNode", ctx, arg)}
}

func (_c *Repository_GetSnapshotsByNode_Call) Run(run func(ctx context.Context, arg graph.GetSnapshotsByNodeParams)) *Repository_GetSnapshotsByNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetSnapshotsByNodeParams))
	})
	return _c
}

func (_c *Repository_GetSnapshotsByNode_Call) Return(_a0 []graph.Snapshot, _a1 error) *Repository_GetSnapshotsByNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetSnapshotsByNode_Call) RunAndReturn(run func(context.Context, graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error)) *Repository_GetSnapshotsByNode_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSnapshot provides a mock function with given fields: ctx, arg
func (_m *Repository) InsertSnapshot(ctx context.Context, arg graph.InsertSnapshotParams) (graph.Snapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSnapshot")
	}

	var r0 graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotParams) (graph.Snapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotParams) graph.Snapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.InsertSnapshotParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSnapshot'
type Repository_InsertSnapshot_Call struct {
	*mock.Call
}

// InsertSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.InsertSnapshotParams
func (_e *Repository_Expecter) InsertSnapshot(ctx interface{}, arg interface{}) *Repository_InsertSnapshot_Call {
	return &Repository_InsertSnapshot_Call{Call: _e.mock.On("InsertSnapshot", ctx, arg)}
}

func (_c *Repository_InsertSnapshot_Call) Run(run func(ctx context.Context, arg graph.InsertSnapshotParams)) *Repository_InsertSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.InsertSnapshotParams))
	})
	return _c
}

func (_c *Repository_InsertSnapshot_Call) Return(_a0 graph.Snapshot, _a1 error) *Repository_InsertSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertSnapshot_Call) RunAndReturn(run func(context.Context, graph.InsertSnapshotParams) (graph.Snapshot, error)) *Repository_InsertSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSnapshotMetadata provides a mock function with given fields: ctx, arg
func (_m *Repository) InsertSnapshotMetadata(ctx context.Context, arg graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSnapshotMetadata")
	}

	var r0 graph.SnapshotMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotMetadataParams) graph.SnapshotMetadata); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.SnapshotMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.InsertSnapshotMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_InsertSnapshotMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSnapshotMetadata'
type Repository_InsertSnapshotMetadata_Call struct {
	*mock.Call
}

// InsertSnapshotMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.InsertSnapshotMetadataParams
func (_e *Repository_Expecter) InsertSnapshotMetadata(ctx interface{}, arg interface{}) *Repository_InsertSnapshotMetadata_Call {
	return &Repository_InsertSnapshotMetadata_Call{Call: _e.mock.On("InsertSnapshotMetadata", ctx, arg)}
}

func (_c *Repository_InsertSnapshotMetadata_Call) Run(run func(ctx context.Context, arg graph.InsertSnapshotMetadataParams)) *Repository_InsertSnapshotMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.InsertSnapshotMetadataParams))
	})
	return _c
}

func (_c *Repository_InsertSnapshotMetadata_Call) Return(_a0 graph.SnapshotMetadata, _a1 error) *Repository_InsertSnapshotMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_InsertSnapshotMetadata_Call) RunAndReturn(run func(context.Context, graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error)) *Repository_InsertSnapshotMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodes provides a mock function with given fields: ctx, arg
func (_m *Repository) ListNodes(ctx context.Context, arg graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesParams) []graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.NodeWithLatestSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.ListNodesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type Repository_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.ListNodesParams
func (_e *Repository_Expecter) ListNodes(ctx interface{}, arg interface{}) *Repository_ListNodes_Call {
	return &Repository_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx, arg)}
}

func (_c *Repository_ListNodes_Call) Run(run func(ctx context.Context, arg graph.ListNodesParams)) *Repository_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.ListNodesParams))
	})
	return _c
}

func (_c *Repository_ListNodes_Call) Return(_a0 []graph.NodeWithLatestSnapshot, _a1 error) *Repository_ListNodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListNodes_Call) RunAndReturn(run func(context.Context, graph.ListNodesParams) ([]graph.NodeWithLatestSnapshot, error)) *Repository_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodesBySnapshotMetadata provides a mock function with given fields: ctx, arg
func (_m *Repository) ListNodesBySnapshotMetadata(ctx context.Context, arg graph.ListNodesBySnapshotMetadataParams) ([]graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListNodesBySnapshotMetadata")
	}

	var r0 []graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesBySnapshotMetadataParams) ([]graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.ListNodesBySnapshotMetadataParams) []graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.NodeWithLatestSnapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.ListNodesBySnapshotMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListNodesBySnapshotMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodesBySnapshotMetadata'
type Repository_ListNodesBySnapshotMetadata_Call struct {
	*mock.Call
}

// ListNodesBySnapshotMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.ListNodesBySnapshotMetadataParams
func (_e *Repository_Expecter) ListNodesBySnapshotMetadata(ctx interface{}, arg interface{}) *Repository_ListNodesBySnapshotMetadata_Call {
	return &Repository_ListNodesBySnapshotMetadata_Call{Call: _e.mock.On("ListNodesBySnapshotMetadata", ctx, arg)}
}

func (_c *Repository_ListNodesBySnapshotMetadata_Call) Run(run func(ctx context.Context, arg graph.ListNodesBySnapshotMetadataParams)) *Repository_ListNodesBySnapshotMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.ListNodesBySnapshotMetadataParams))
	})
	return _c
}

func (_c *Repository_ListNodesBySnapshotMetadata_Call) Return(_a0 []graph.NodeWithLatestSnapshot, _a1 error) *Repository_ListNodesBySnapshotMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListNodesBySnapshotMetadata_Call) RunAndReturn(run func(context.Context, graph.ListNodesBySnapshotMetadataParams) ([]graph.NodeWithLatestSnapshot, error)) *Repository_ListNodesBySnapshotMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNodeData provides a mock function with given fields: ctx, arg
func (_m *Repository) UpdateNodeData(ctx context.Context, arg graph.UpdateNodeDataParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeData")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpdateNodeDataParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpdateNodeDataParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.UpdateNodeDataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpdateNodeData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNodeData'
type Repository_UpdateNodeData_Call struct {
	*mock.Call
}

// UpdateNodeData is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpdateNodeDataParams
func (_e *Repository_Expecter) UpdateNodeData(ctx interface{}, arg interface{}) *Repository_UpdateNodeData_Call {
	return &Repository_UpdateNodeData_Call{Call: _e.mock.On("UpdateNodeData", ctx, arg)}
}

func (_c *Repository_UpdateNodeData_Call) Run(run func(ctx context.Context, arg graph.UpdateNodeDataParams)) *Repository_UpdateNodeData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpdateNodeDataParams))
	})
	return _c
}

func (_c *Repository_UpdateNodeData_Call) Return(_a0 graph.Node, _a1 error) *Repository_UpdateNodeData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpdateNodeData_Call) RunAndReturn(run func(context.Context, graph.UpdateNodeDataParams) (graph.Node, error)) *Repository_UpdateNodeData_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEdge provides a mock function with given fields: ctx, arg
func (_m *Repository) UpsertEdge(ctx context.Context, arg graph.UpsertEdgeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEdge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertEdgeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpsertEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEdge'
type Repository_UpsertEdge_Call struct {
	*mock.Call
}

// UpsertEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpsertEdgeParams
func (_e *Repository_Expecter) UpsertEdge(ctx interface{}, arg interface{}) *Repository_UpsertEdge_Call {
	return &Repository_UpsertEdge_Call{Call: _e.mock.On("UpsertEdge", ctx, arg)}
}

func (_c *Repository_UpsertEdge_Call) Run(run func(ctx context.Context, arg graph.UpsertEdgeParams)) *Repository_UpsertEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpsertEdgeParams))
	})
	return _c
}

func (_c *Repository_UpsertEdge_Call) Return(_a0 error) *Repository_UpsertEdge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpsertEdge_Call) RunAndReturn(run func(context.Context, graph.UpsertEdgeParams) error) *Repository_UpsertEdge_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertNode provides a mock function with given fields: ctx, arg
func (_m *Repository) UpsertNode(ctx context.Context, arg graph.UpsertNodeParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertNode")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertNodeParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.UpsertNodeParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.UpsertNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpsertNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertNode'
type Repository_UpsertNode_Call struct {
	*mock.Call
}

// UpsertNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.UpsertNodeParams
func (_e *Repository_Expecter) UpsertNode(ctx interface{}, arg interface{}) *Repository_UpsertNode_Call {
	return &Repository_UpsertNode_Call{Call: _e.mock.On("UpsertNode", ctx, arg)}
}

func (_c *Repository_UpsertNode_Call) Run(run func(ctx context.Context, arg graph.UpsertNodeParams)) *Repository_UpsertNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.UpsertNodeParams))
	})
	return _c
}

func (_c *Repository_UpsertNode_Call) Return(_a0 graph.Node, _a1 error) *Repository_UpsertNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpsertNode_Call) RunAndReturn(run func(context.Context, graph.UpsertNodeParams) (graph.Node, error)) *Repository_UpsertNode_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
