// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// SnapshotWriter is an autogenerated mock type for the SnapshotWriter type
type SnapshotWriter struct {
	mock.Mock
}

type SnapshotWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotWriter) EXPECT() *SnapshotWriter_Expecter {
	return &SnapshotWriter_Expecter{mock: &_m.Mock}
}

// CleanupExpiredSnapshots provides a mock function with given fields: ctx, arg
func (_m *SnapshotWriter) CleanupExpiredSnapshots(ctx context.Context, arg graph.CleanupExpiredSnapshotsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredSnapshots")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.CleanupExpiredSnapshotsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SnapshotWriter_CleanupExpiredSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpiredSnapshots'
type SnapshotWriter_CleanupExpiredSnapshots_Call struct {
	*mock.Call
}

// CleanupExpiredSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.CleanupExpiredSnapshotsParams
func (_e *SnapshotWriter_Expecter) CleanupExpiredSnapshots(ctx interface{}, arg interface{}) *SnapshotWriter_CleanupExpiredSnapshots_Call {
	return &SnapshotWriter_CleanupExpiredSnapshots_Call{Call: _e.mock.On("CleanupExpiredSnapshots", ctx, arg)}
}

func (_c *SnapshotWriter_CleanupExpiredSnapshots_Call) Run(run func(ctx context.Context, arg graph.CleanupExpiredSnapshotsParams)) *SnapshotWriter_CleanupExpiredSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.CleanupExpiredSnapshotsParams))
	})
	return _c
}

func (_c *SnapshotWriter_CleanupExpiredSnapshots_Call) Return(_a0 error) *SnapshotWriter_CleanupExpiredSnapshots_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotWriter_CleanupExpiredSnapshots_Call) RunAndReturn(run func(context.Context, graph.CleanupExpiredSnapshotsParams) error) *SnapshotWriter_CleanupExpiredSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSnapshot provides a mock function with given fields: ctx, arg
func (_m *SnapshotWriter) InsertSnapshot(ctx context.Context, arg graph.InsertSnapshotParams) (graph.Snapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSnapshot")
	}

	var r0 graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotParams) (graph.Snapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotParams) graph.Snapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.InsertSnapshotParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotWriter_InsertSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSnapshot'
type SnapshotWriter_InsertSnapshot_Call struct {
	*mock.Call
}

// InsertSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.InsertSnapshotParams
func (_e *SnapshotWriter_Expecter) InsertSnapshot(ctx interface{}, arg interface{}) *SnapshotWriter_InsertSnapshot_Call {
	return &SnapshotWriter_InsertSnapshot_Call{Call: _e.mock.On("InsertSnapshot", ctx, arg)}
}

func (_c *SnapshotWriter_InsertSnapshot_Call) Run(run func(ctx context.Context, arg graph.InsertSnapshotParams)) *SnapshotWriter_InsertSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.InsertSnapshotParams))
	})
	return _c
}

func (_c *SnapshotWriter_InsertSnapshot_Call) Return(_a0 graph.Snapshot, _a1 error) *SnapshotWriter_InsertSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotWriter_InsertSnapshot_Call) RunAndReturn(run func(context.Context, graph.InsertSnapshotParams) (graph.Snapshot, error)) *SnapshotWriter_InsertSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSnapshotMetadata provides a mock function with given fields: ctx, arg
func (_m *SnapshotWriter) InsertSnapshotMetadata(ctx context.Context, arg graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSnapshotMetadata")
	}

	var r0 graph.SnapshotMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.InsertSnapshotMetadataParams) graph.SnapshotMetadata); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.SnapshotMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.InsertSnapshotMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotWriter_InsertSnapshotMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSnapshotMetadata'
type SnapshotWriter_InsertSnapshotMetadata_Call struct {
	*mock.Call
}

// InsertSnapshotMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.InsertSnapshotMetadataParams
func (_e *SnapshotWriter_Expecter) InsertSnapshotMetadata(ctx interface{}, arg interface{}) *SnapshotWriter_InsertSnapshotMetadata_Call {
	return &SnapshotWriter_InsertSnapshotMetadata_Call{Call: _e.mock.On("InsertSnapshotMetadata", ctx, arg)}
}

func (_c *SnapshotWriter_InsertSnapshotMetadata_Call) Run(run func(ctx context.Context, arg graph.InsertSnapshotMetadataParams)) *SnapshotWriter_InsertSnapshotMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.InsertSnapshotMetadataParams))
	})
	return _c
}

func (_c *SnapshotWriter_InsertSnapshotMetadata_Call) Return(_a0 graph.SnapshotMetadata, _a1 error) *SnapshotWriter_InsertSnapshotMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotWriter_InsertSnapshotMetadata_Call) RunAndReturn(run func(context.Context, graph.InsertSnapshotMetadataParams) (graph.SnapshotMetadata, error)) *SnapshotWriter_InsertSnapshotMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotWriter creates a new instance of SnapshotWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotWriter {
	mock := &SnapshotWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
