// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"
	mock "github.com/stretchr/testify/mock"
)

// SnapshotReader is an autogenerated mock type for the SnapshotReader type
type SnapshotReader struct {
	mock.Mock
}

type SnapshotReader_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotReader) EXPECT() *SnapshotReader_Expecter {
	return &SnapshotReader_Expecter{mock: &_m.Mock}
}

// GetLatestSnapshot provides a mock function with given fields: ctx, nodeID
func (_m *SnapshotReader) GetLatestSnapshot(ctx context.Context, nodeID int64) (graph.Snapshot, error) {
	ret := _m.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSnapshot")
	}

	var r0 graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (graph.Snapshot, error)); ok {
		return rf(ctx, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) graph.Snapshot); ok {
		r0 = rf(ctx, nodeID)
	} else {
		r0 = ret.Get(0).(graph.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotReader_GetLatestSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSnapshot'
type SnapshotReader_GetLatestSnapshot_Call struct {
	*mock.Call
}

// GetLatestSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID int64
func (_e *SnapshotReader_Expecter) GetLatestSnapshot(ctx interface{}, nodeID interface{}) *SnapshotReader_GetLatestSnapshot_Call {
	return &SnapshotReader_GetLatestSnapshot_Call{Call: _e.mock.On("GetLatestSnapshot", ctx, nodeID)}
}

func (_c *SnapshotReader_GetLatestSnapshot_Call) Run(run func(ctx context.Context, nodeID int64)) *SnapshotReader_GetLatestSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *SnapshotReader_GetLatestSnapshot_Call) Return(_a0 graph.Snapshot, _a1 error) *SnapshotReader_GetLatestSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotReader_GetLatestSnapshot_Call) RunAndReturn(run func(context.Context, int64) (graph.Snapshot, error)) *SnapshotReader_GetLatestSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeWithLatestSnapshot provides a mock function with given fields: ctx, arg
func (_m *SnapshotReader) GetNodeWithLatestSnapshot(ctx context.Context, arg graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeWithLatestSnapshot")
	}

	var r0 graph.NodeWithLatestSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) graph.NodeWithLatestSnapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.NodeWithLatestSnapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetNodeWithLatestSnapshotParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotReader_GetNodeWithLatestSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeWithLatestSnapshot'
type SnapshotReader_GetNodeWithLatestSnapshot_Call struct {
	*mock.Call
}

// GetNodeWithLatestSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetNodeWithLatestSnapshotParams
func (_e *SnapshotReader_Expecter) GetNodeWithLatestSnapshot(ctx interface{}, arg interface{}) *SnapshotReader_GetNodeWithLatestSnapshot_Call {
	return &SnapshotReader_GetNodeWithLatestSnapshot_Call{Call: _e.mock.On("GetNodeWithLatestSnapshot", ctx, arg)}
}

func (_c *SnapshotReader_GetNodeWithLatestSnapshot_Call) Run(run func(ctx context.Context, arg graph.GetNodeWithLatestSnapshotParams)) *SnapshotReader_GetNodeWithLatestSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetNodeWithLatestSnapshotParams))
	})
	return _c
}

func (_c *SnapshotReader_GetNodeWithLatestSnapshot_Call) Return(_a0 graph.NodeWithLatestSnapshot, _a1 error) *SnapshotReader_GetNodeWithLatestSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotReader_GetNodeWithLatestSnapshot_Call) RunAndReturn(run func(context.Context, graph.GetNodeWithLatestSnapshotParams) (graph.NodeWithLatestSnapshot, error)) *SnapshotReader_GetNodeWithLatestSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshotsByNode provides a mock function with given fields: ctx, arg
func (_m *SnapshotReader) GetSnapshotsByNode(ctx context.Context, arg graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshotsByNode")
	}

	var r0 []graph.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetSnapshotsByNodeParams) []graph.Snapshot); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Snapshot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetSnapshotsByNodeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotReader_GetSnapshotsByNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshotsByNode'
type SnapshotReader_GetSnapshotsByNode_Call struct {
	*mock.Call
}

// GetSnapshotsByNode is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetSnapshotsByNodeParams
func (_e *SnapshotReader_Expecter) GetSnapshotsByNode(ctx interface{}, arg interface{}) *SnapshotReader_GetSnapshotsByNode_Call {
	return &SnapshotReader_GetSnapshotsByNode_Call{Call: _e.mock.On("GetSnapshotsByNode", ctx, arg)}
}

func (_c *SnapshotReader_GetSnapshotsByNode_Call) Run(run func(ctx context.Context, arg graph.GetSnapshotsByNodeParams)) *SnapshotReader_GetSnapshotsByNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetSnapshotsByNodeParams))
	})
	return _c
}

func (_c *SnapshotReader_GetSnapshotsByNode_Call) Return(_a0 []graph.Snapshot, _a1 error) *SnapshotReader_GetSnapshotsByNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotReader_GetSnapshotsByNode_Call) RunAndReturn(run func(context.Context, graph.GetSnapshotsByNodeParams) ([]graph.Snapshot, error)) *SnapshotReader_GetSnapshotsByNode_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotReader creates a new instance of SnapshotReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotReader {
	mock := &SnapshotReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
