run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats: colored-line-number

linters:
  enable:
    - revive
    - errcheck
    - unused
    - staticcheck
    - ineffassign
    - govet
    - gosimple
    - bodyclose
    - gci
    - gofumpt

issues:
  exclude-use-default: false
  exclude-rules:
    - path: /*.go
      text: "package-comments: should have a package comment"
      linters:
        - revive
    - path: /*.go
      text: 'SA1019: filter.DataType is deprecated'
    - path: /*.go
      text: 'SA1019: g.client.RetrieveIngestionLogs is deprecated'

severity:
  default-severity: error

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/netboxlabs/diode)
    custom-order: true
  go-fumpt:
    extra-rules: true
