version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      color: true
linters:
  enable:
    - bodyclose
    - revive
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: /*.go
        text: 'package-comments: should have a package comment'
      - linters:
          - revive
        path: errors/errors.go
        text: 'var-naming: avoid package names that conflict'
      - path: /*.go
        text: 'SA1019: filter.DataType is deprecated'
      - path: /*.go
        text: 'SA1019: g.client.RetrieveIngestionLogs is deprecated'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netboxlabs/diode)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
