[project]
name = "netboxlabs-diode"
version = "1.2.0"
description = "Diode is a data ingestion service for NetBox that greatly simplifies and enhances the process of adding and updating data in NetBox"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "NetBox Labs", email = "support@netboxlabs.com" }
]
maintainers = [
    { name = "NetBox Labs", email = "support@netboxlabs.com" }
]

dependencies = []

[project.optional-dependencies]
dev = ["mkdocs", "mkdocs-material"]
test = ["pytest", "pytest-cov", "coverage"]

[project.urls]
"Homepage" = "https://netboxlabs.com/"
"Repository" = "https://github.com/netboxlabs/diode"
"Issues" = "https://github.com/netboxlabs/diode/issues"
"Documentation" = "https://github.com/netboxlabs/diode/docs"

[project.scripts]

[tool.setuptools]
packages = []
license-files = ["LICENSE.md"]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta" 