# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diode/v1/prefix.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from netboxlabs.diode.sdk.diode.v1 import site_pb2 as diode_dot_v1_dot_site__pb2
from netboxlabs.diode.sdk.diode.v1 import tag_pb2 as diode_dot_v1_dot_tag__pb2
from netboxlabs.diode.sdk.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64iode/v1/prefix.proto\x12\x08\x64iode.v1\x1a\x13\x64iode/v1/site.proto\x1a\x12\x64iode/v1/tag.proto\x1a\x17validate/validate.proto\"\xbe\x02\n\x06Prefix\x12\x1f\n\x06prefix\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02p\x01R\x06prefix\x12\"\n\x04site\x18\x02 \x01(\x0b\x32\x0e.diode.v1.SiteR\x04site\x12\x46\n\x06status\x18\x03 \x01(\tB.\xfa\x42+r)R\x06\x61\x63tiveR\tcontainerR\x08reservedR\ndeprecatedR\x06status\x12\x17\n\x07is_pool\x18\x04 \x01(\x08R\x06isPool\x12#\n\rmark_utilized\x18\x05 \x01(\x08R\x0cmarkUtilized\x12*\n\x0b\x64\x65scription\x18\x06 \x01(\tB\x08\xfa\x42\x05r\x03\x18\xc8\x01R\x0b\x64\x65scription\x12\x1a\n\x08\x63omments\x18\x07 \x01(\tR\x08\x63omments\x12!\n\x04tags\x18\x08 \x03(\x0b\x32\r.diode.v1.TagR\x04tagsB;Z9github.com/netboxlabs/diode/diode-sdk-go/diode/v1/diodepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diode.v1.prefix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/netboxlabs/diode/diode-sdk-go/diode/v1/diodepb'
  _globals['_PREFIX'].fields_by_name['prefix']._loaded_options = None
  _globals['_PREFIX'].fields_by_name['prefix']._serialized_options = b'\372B\004r\002p\001'
  _globals['_PREFIX'].fields_by_name['status']._loaded_options = None
  _globals['_PREFIX'].fields_by_name['status']._serialized_options = b'\372B+r)R\006activeR\tcontainerR\010reservedR\ndeprecated'
  _globals['_PREFIX'].fields_by_name['description']._loaded_options = None
  _globals['_PREFIX'].fields_by_name['description']._serialized_options = b'\372B\005r\003\030\310\001'
  _globals['_PREFIX']._serialized_start=102
  _globals['_PREFIX']._serialized_end=420
# @@protoc_insertion_point(module_scope)
