// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

type Metrics_Expecter struct {
	mock *mock.Mock
}

func (_m *Metrics) EXPECT() *Metrics_Expecter {
	return &Metrics_Expecter{mock: &_m.Mock}
}

// RecordIngestEntities provides a mock function with given fields: ctx, count
func (_m *Metrics) RecordIngestEntities(ctx context.Context, count int64) {
	_m.Called(ctx, count)
}

// Metrics_RecordIngestEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIngestEntities'
type Metrics_RecordIngestEntities_Call struct {
	*mock.Call
}

// RecordIngestEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - count int64
func (_e *Metrics_Expecter) RecordIngestEntities(ctx interface{}, count interface{}) *Metrics_RecordIngestEntities_Call {
	return &Metrics_RecordIngestEntities_Call{Call: _e.mock.On("RecordIngestEntities", ctx, count)}
}

func (_c *Metrics_RecordIngestEntities_Call) Run(run func(ctx context.Context, count int64)) *Metrics_RecordIngestEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *Metrics_RecordIngestEntities_Call) Return() *Metrics_RecordIngestEntities_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_RecordIngestEntities_Call) RunAndReturn(run func(context.Context, int64)) *Metrics_RecordIngestEntities_Call {
	_c.Run(run)
	return _c
}

// RecordIngestRequest provides a mock function with given fields: ctx, success
func (_m *Metrics) RecordIngestRequest(ctx context.Context, success bool) {
	_m.Called(ctx, success)
}

// Metrics_RecordIngestRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIngestRequest'
type Metrics_RecordIngestRequest_Call struct {
	*mock.Call
}

// RecordIngestRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - success bool
func (_e *Metrics_Expecter) RecordIngestRequest(ctx interface{}, success interface{}) *Metrics_RecordIngestRequest_Call {
	return &Metrics_RecordIngestRequest_Call{Call: _e.mock.On("RecordIngestRequest", ctx, success)}
}

func (_c *Metrics_RecordIngestRequest_Call) Run(run func(ctx context.Context, success bool)) *Metrics_RecordIngestRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *Metrics_RecordIngestRequest_Call) Return() *Metrics_RecordIngestRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_RecordIngestRequest_Call) RunAndReturn(run func(context.Context, bool)) *Metrics_RecordIngestRequest_Call {
	_c.Run(run)
	return _c
}

// SetServiceInfo provides a mock function with given fields: ctx, version
func (_m *Metrics) SetServiceInfo(ctx context.Context, version string) {
	_m.Called(ctx, version)
}

// Metrics_SetServiceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServiceInfo'
type Metrics_SetServiceInfo_Call struct {
	*mock.Call
}

// SetServiceInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *Metrics_Expecter) SetServiceInfo(ctx interface{}, version interface{}) *Metrics_SetServiceInfo_Call {
	return &Metrics_SetServiceInfo_Call{Call: _e.mock.On("SetServiceInfo", ctx, version)}
}

func (_c *Metrics_SetServiceInfo_Call) Run(run func(ctx context.Context, version string)) *Metrics_SetServiceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Metrics_SetServiceInfo_Call) Return() *Metrics_SetServiceInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *Metrics_SetServiceInfo_Call) RunAndReturn(run func(context.Context, string)) *Metrics_SetServiceInfo_Call {
	_c.Run(run)
	return _c
}

// NewMetrics creates a new instance of Metrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metrics {
	mock := &Metrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
