// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: diode/v1/device_type.proto

package diodepb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DeviceType with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceType) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceType with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceTypeMultiError, or
// nil if none found.
func (m *DeviceType) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceType) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetManufacturer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceTypeValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceTypeValidationError{
					field:  "Manufacturer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetManufacturer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceTypeValidationError{
				field:  "Manufacturer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if l := utf8.RuneCountInString(m.GetModel()); l < 1 || l > 100 {
		err := DeviceTypeValidationError{
			field:  "Model",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetSlug()); l < 1 || l > 100 {
		err := DeviceTypeValidationError{
			field:  "Slug",
			reason: "value length must be between 1 and 100 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_DeviceType_Slug_Pattern.MatchString(m.GetSlug()) {
		err := DeviceTypeValidationError{
			field:  "Slug",
			reason: "value does not match regex pattern \"^[-a-zA-Z0-9_]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeviceTypeMultiError(errors)
	}

	return nil
}

// DeviceTypeMultiError is an error wrapping multiple validation errors
// returned by DeviceType.ValidateAll() if the designated constraints aren't met.
type DeviceTypeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceTypeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceTypeMultiError) AllErrors() []error { return m }

// DeviceTypeValidationError is the validation error returned by
// DeviceType.Validate if the designated constraints aren't met.
type DeviceTypeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceTypeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceTypeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceTypeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceTypeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceTypeValidationError) ErrorName() string { return "DeviceTypeValidationError" }

// Error satisfies the builtin error interface
func (e DeviceTypeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceType.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceTypeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceTypeValidationError{}

var _DeviceType_Slug_Pattern = regexp.MustCompile("^[-a-zA-Z0-9_]+$")
