package main

const entityMappingTemplate = `// Code generated by protograph. DO NOT EDIT.

package {{.Package}}

import (
	"github.com/netboxlabs/diode/diode-server/gen/diode/v1/diodepb"
)

// CreateEntityFromInterface creates a diodepb.Entity from a typed interface value.
// This replaces the large manual switch statements in the GraphBuilder.
func CreateEntityFromInterface(fieldValue interface{}) *diodepb.Entity {
	if fieldValue == nil {
		return nil
	}

	switch v := fieldValue.(type) {
{{- range .Entities}}
	case {{.PbType}}:
		return &diodepb.Entity{Entity: &diodepb.{{.OneofField}}{ {{- .StructField}}: v}}
{{- end}}
	default:
		return nil
	}
}

// GetEntityTypeName returns the entity type name for a given interface value.
// This is useful for debugging and logging.
func GetEntityTypeName(fieldValue interface{}) string {
	if fieldValue == nil {
		return ""
	}

	switch fieldValue.(type) {
{{- range .Entities}}
	case {{.PbType}}:
		return "{{.Name}}"
{{- end}}
	default:
		return "unknown"
	}
}

// IsKnownEntityType checks if the given interface value is a known entity type.
func IsKnownEntityType(fieldValue interface{}) bool {
	if fieldValue == nil {
		return false
	}

	switch fieldValue.(type) {
{{- range .Entities}}
	case {{.PbType}}:
		return true
{{- end}}
	default:
		return false
	}
}

// GetAllEntityTypes returns a list of all known entity type names.
// This is useful for documentation and testing.
func GetAllEntityTypes() []string {
	return []string{
{{- range .Entities}}
		"{{.Name}}",
{{- end}}
	}
}
`
