# Generated by Django 4.2.10 on 2024-02-27 12:54

from django.db import migrations, models
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
            ],
            options={
                'permissions': (('view_objectstate', 'Can view ObjectState'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
