// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	netboxdiodeplugin "github.com/netboxlabs/diode/diode-server/netboxdiodeplugin"
	mock "github.com/stretchr/testify/mock"
)

// NetBoxAPI is an autogenerated mock type for the NetBoxAPI type
type NetBoxAPI struct {
	mock.Mock
}

type NetBoxAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *NetBoxAPI) EXPECT() *NetBoxAPI_Expecter {
	return &NetBoxAPI_Expecter{mock: &_m.Mock}
}

// BulkPlan provides a mock function with given fields: _a0, _a1
func (_m *NetBoxAPI) BulkPlan(_a0 context.Context, _a1 netboxdiodeplugin.BulkPlanRequest) (*netboxdiodeplugin.BulkPlanResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkPlan")
	}

	var r0 *netboxdiodeplugin.BulkPlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, netboxdiodeplugin.BulkPlanRequest) (*netboxdiodeplugin.BulkPlanResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, netboxdiodeplugin.BulkPlanRequest) *netboxdiodeplugin.BulkPlanResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netboxdiodeplugin.BulkPlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, netboxdiodeplugin.BulkPlanRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetBoxAPI_BulkPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkPlan'
type NetBoxAPI_BulkPlan_Call struct {
	*mock.Call
}

// BulkPlan is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 netboxdiodeplugin.BulkPlanRequest
func (_e *NetBoxAPI_Expecter) BulkPlan(_a0 interface{}, _a1 interface{}) *NetBoxAPI_BulkPlan_Call {
	return &NetBoxAPI_BulkPlan_Call{Call: _e.mock.On("BulkPlan", _a0, _a1)}
}

func (_c *NetBoxAPI_BulkPlan_Call) Run(run func(_a0 context.Context, _a1 netboxdiodeplugin.BulkPlanRequest)) *NetBoxAPI_BulkPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(netboxdiodeplugin.BulkPlanRequest))
	})
	return _c
}

func (_c *NetBoxAPI_BulkPlan_Call) Return(_a0 *netboxdiodeplugin.BulkPlanResponse, _a1 error) *NetBoxAPI_BulkPlan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetBoxAPI_BulkPlan_Call) RunAndReturn(run func(context.Context, netboxdiodeplugin.BulkPlanRequest) (*netboxdiodeplugin.BulkPlanResponse, error)) *NetBoxAPI_BulkPlan_Call {
	_c.Call.Return(run)
	return _c
}

// BulkPlanApply provides a mock function with given fields: _a0, _a1
func (_m *NetBoxAPI) BulkPlanApply(_a0 context.Context, _a1 netboxdiodeplugin.BulkPlanApplyRequest) (*netboxdiodeplugin.BulkPlanApplyResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkPlanApply")
	}

	var r0 *netboxdiodeplugin.BulkPlanApplyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, netboxdiodeplugin.BulkPlanApplyRequest) (*netboxdiodeplugin.BulkPlanApplyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, netboxdiodeplugin.BulkPlanApplyRequest) *netboxdiodeplugin.BulkPlanApplyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netboxdiodeplugin.BulkPlanApplyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, netboxdiodeplugin.BulkPlanApplyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetBoxAPI_BulkPlanApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkPlanApply'
type NetBoxAPI_BulkPlanApply_Call struct {
	*mock.Call
}

// BulkPlanApply is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 netboxdiodeplugin.BulkPlanApplyRequest
func (_e *NetBoxAPI_Expecter) BulkPlanApply(_a0 interface{}, _a1 interface{}) *NetBoxAPI_BulkPlanApply_Call {
	return &NetBoxAPI_BulkPlanApply_Call{Call: _e.mock.On("BulkPlanApply", _a0, _a1)}
}

func (_c *NetBoxAPI_BulkPlanApply_Call) Run(run func(_a0 context.Context, _a1 netboxdiodeplugin.BulkPlanApplyRequest)) *NetBoxAPI_BulkPlanApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(netboxdiodeplugin.BulkPlanApplyRequest))
	})
	return _c
}

func (_c *NetBoxAPI_BulkPlanApply_Call) Return(_a0 *netboxdiodeplugin.BulkPlanApplyResponse, _a1 error) *NetBoxAPI_BulkPlanApply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetBoxAPI_BulkPlanApply_Call) RunAndReturn(run func(context.Context, netboxdiodeplugin.BulkPlanApplyRequest) (*netboxdiodeplugin.BulkPlanApplyResponse, error)) *NetBoxAPI_BulkPlanApply_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultBranch provides a mock function with given fields: _a0
func (_m *NetBoxAPI) GetDefaultBranch(_a0 context.Context) (*netboxdiodeplugin.Branch, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultBranch")
	}

	var r0 *netboxdiodeplugin.Branch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*netboxdiodeplugin.Branch, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *netboxdiodeplugin.Branch); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netboxdiodeplugin.Branch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetBoxAPI_GetDefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultBranch'
type NetBoxAPI_GetDefaultBranch_Call struct {
	*mock.Call
}

// GetDefaultBranch is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *NetBoxAPI_Expecter) GetDefaultBranch(_a0 interface{}) *NetBoxAPI_GetDefaultBranch_Call {
	return &NetBoxAPI_GetDefaultBranch_Call{Call: _e.mock.On("GetDefaultBranch", _a0)}
}

func (_c *NetBoxAPI_GetDefaultBranch_Call) Run(run func(_a0 context.Context)) *NetBoxAPI_GetDefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *NetBoxAPI_GetDefaultBranch_Call) Return(_a0 *netboxdiodeplugin.Branch, _a1 error) *NetBoxAPI_GetDefaultBranch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetBoxAPI_GetDefaultBranch_Call) RunAndReturn(run func(context.Context) (*netboxdiodeplugin.Branch, error)) *NetBoxAPI_GetDefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}

// NewNetBoxAPI creates a new instance of NetBoxAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetBoxAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetBoxAPI {
	mock := &NetBoxAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
