apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.diodeIngester.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.diodeIngester.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.diodeIngester.serviceName }}
  ports:
    - name: grpc
      port: {{ .Values.diodeIngester.containerPort }}
      targetPort: {{ .Values.diodeIngester.containerPort }}
      protocol: TCP
