{{- if .Values.diodeAuth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "diode.auth.servicename" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app: {{ include "diode.auth.servicename" . }}
    app.kubernetes.io/component: {{ include "diode.auth.servicename" . }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "diode.auth.servicename" . }}
  ports:
    - name: http
      port: {{ .Values.diodeAuth.containerPort }}
      targetPort: {{ .Values.diodeAuth.containerPort }}
      protocol: TCP
{{- end }}
