{{- if and .Values.postgresql.enabled .Values.postgresql.primary.persistence.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diode.postgresql.initdb.scriptsconfigmap" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  init_diode_databases.sh: |
    #!/bin/bash
    set -euo pipefail

    echo "Initializing users and databases..."
    
    POSTGRES_USER=$(cat /opt/bitnami/postgresql/secrets/postgres-username)
    POSTGRES_DB_NAME=$(cat /opt/bitnami/postgresql/secrets/postgres-database)
    export PGPASSWORD=$(cat /opt/bitnami/postgresql/secrets/postgres-password)

    DIODE_POSTGRES_USER=$(cat /opt/bitnami/postgresql/secrets/diode-username)
    DIODE_POSTGRES_PASSWORD=$(cat /opt/bitnami/postgresql/secrets/diode-password)
    DIODE_POSTGRES_DB_NAME=$(cat /opt/bitnami/postgresql/secrets/diode-database)

    HYDRA_POSTGRES_USER=$(cat /opt/bitnami/postgresql/secrets/hydra-username)
    HYDRA_POSTGRES_PASSWORD=$(cat /opt/bitnami/postgresql/secrets/hydra-password)
    HYDRA_POSTGRES_DB_NAME=$(cat /opt/bitnami/postgresql/secrets/hydra-database)

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB_NAME" <<-EOSQL
        -- diode
        CREATE USER ${DIODE_POSTGRES_USER} WITH PASSWORD '${DIODE_POSTGRES_PASSWORD}';
        CREATE DATABASE ${DIODE_POSTGRES_DB_NAME} OWNER ${DIODE_POSTGRES_USER};
        GRANT ALL PRIVILEGES ON DATABASE ${DIODE_POSTGRES_DB_NAME} TO ${DIODE_POSTGRES_USER};

        -- hydra
        CREATE USER ${HYDRA_POSTGRES_USER} WITH PASSWORD '${HYDRA_POSTGRES_PASSWORD}';
        CREATE DATABASE ${HYDRA_POSTGRES_DB_NAME} OWNER ${HYDRA_POSTGRES_USER};
        GRANT ALL PRIVILEGES ON DATABASE ${HYDRA_POSTGRES_DB_NAME} TO ${HYDRA_POSTGRES_USER};
    EOSQL

    echo "Users and databases initialized successfully" 
{{- end }}
