{{- if and .Values.diodeReconciler.enabled .Values.diodeReconciler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diode.reconciler.serviceaccountname" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "diode.reconciler.servicename" . }}
{{- end }} 
