{{- if .Values.diodeReconciler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diode.reconciler.servicename" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app: {{ include "diode.reconciler.servicename" . }}
    app.kubernetes.io/component: {{ include "diode.reconciler.servicename" . }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.diodeReconciler.replicaCount }}
  selector:
    matchLabels:
      {{- include "diode.selectorlabels" . | nindent 6 }}
      app: {{ include "diode.reconciler.servicename" . }}
      app.kubernetes.io/component: {{ include "diode.reconciler.servicename" . }}
  template:
    metadata:
      annotations:
        checksum/config-reconciler: {{ include (printf "%s/%s-reconciler-configmap.yaml" $.Template.BasePath (include "diode.name" .)) . | sha256sum }}
      labels:
        {{- include "diode.selectorlabels" . | nindent 8 }}
        app: {{ include "diode.reconciler.servicename" . }}
        app.kubernetes.io/component: {{ include "diode.reconciler.servicename" . }}
    spec:
      serviceAccountName: {{ include "diode.reconciler.serviceaccountname" . }}
      {{- if .Values.diodeReconciler.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.diodeReconciler.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.redis.enabled }}
        - name: wait-for-redis
          image: {{ include "diode.busybox.image" . }}
          imagePullPolicy: {{ include "diode.busybox.imagepullpolicy" . }}
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "diode.redis.hostname" . }} {{ include "diode.redis.port" . }}; do
                echo "Waiting for Redis server";
                sleep 3;
              done;
              echo "Redis server is up and running";
        {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-postgres
          image: {{ include "diode.busybox.image" . }}
          imagePullPolicy: {{ include "diode.busybox.imagepullpolicy" . }}
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "diode.postgresql.hostname" . }} {{ include "diode.postgresql.port" . }}; do
                echo "Waiting for PostgreSQL server";
                sleep 3;
              done;
              echo "PostgreSQL server is up and running";
        {{- end }}
      containers:
        - name: {{ include "diode.reconciler.servicename" . }}
          image: "{{ .Values.diodeReconciler.image.repository }}:{{ .Values.diodeReconciler.image.tag }}"
          imagePullPolicy: {{ .Values.diodeReconciler.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.diodeReconciler.containerPort | default 8081 }}
          {{- with .Values.diodeReconciler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.diodeReconciler.resources }}
          resources:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- if .Values.diodeReconciler.extraEnvs }}
          env: {{- include "common.tplvalues.render" (dict "value" .Values.diodeReconciler.extraEnvs "context" $) | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "diode.reconciler.configmap" . }}
            - secretRef:
                name: {{ include "diode.reconciler.secret" . }}
            - secretRef:
                name: {{ include "diode.auth.oauth2.secret" . }}
          volumeMounts:
            - name: oauth2-secret
              mountPath: /etc/config/oauth2/client
              readOnly: true
      volumes:
        - name: oauth2-secret
          secret:
            secretName: {{ include "diode.auth.oauth2.secret" . }}
{{- end }} 
