{{- if .Values.diodeReconciler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.diodeReconciler.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.diodeReconciler.serviceName }}
{{- end -}}
