{{- if .Values.diodeIngester.enabled -}}
{{- $config := index .Values.diodeIngester.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diode.ingester.configmap" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "diode.ingester.servicename" . }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  GRPC_PORT: {{ .Values.diodeIngester.containerPort | default "8081" | quote }}
  LOGGING_LEVEL: {{ $config.loggingLevel | default "INFO" | quote }}
  SENTRY_DSN: {{ $config.sentryDsn | quote }}
  REDIS_HOST: {{ include "diode.redis.hostname" . | quote }}
  REDIS_PORT: {{ include "diode.redis.port" . | quote }}
  REDIS_USERNAME: {{ include "diode.redis.username" . | quote }}
  {{- if and .Values.externalRedis.tls .Values.externalRedis.tls.enabled }}
  REDIS_TLS_ENABLED: "true"
  REDIS_TLS_SKIP_VERIFY: {{ .Values.externalRedis.tls.skipVerify | default false | quote }}
  REDIS_TLS_CA_PATH: {{ .Values.externalRedis.tls.caPath | default "" | quote }}
  REDIS_TLS_CLIENT_KEY_PATH: {{ .Values.externalRedis.tls.clientKeyPath | default "" | quote }}
  REDIS_TLS_CLIENT_CERT_PATH: {{ .Values.externalRedis.tls.clientCertPath | default "" | quote }}
  {{- end }}
  REDIS_STREAM_DB: {{ $config.redisStreamDb | default "1" | quote }}
  TELEMETRY_METRICS_EXPORTER: {{ $config.telemetryMetricsExporter | quote }}
  TELEMETRY_TRACES_EXPORTER: {{ $config.telemetryTracesExporter | default "none" | quote }}
  TELEMETRY_ENVIRONMENT: {{ $config.telemetryEnvironment | default .Values.diode.environment | quote }}
{{- end }}
