{{- if .Values.diodeIngester.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diode.ingester.servicename" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app: {{ include "diode.ingester.servicename" . }}
    app.kubernetes.io/component: {{ include "diode.ingester.servicename" . }}
  {{- if or .Values.global.commonAnnotations .Values.diodeIngester.annotations }}
  annotations:
    {{- if .Values.diodeIngester.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.diodeIngester.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{-  end }}
spec:
  replicas: {{ .Values.diodeIngester.replicaCount }}
  selector:
    matchLabels:
      {{- include "diode.selectorlabels" . | nindent 6 }}
      app: {{ include "diode.ingester.servicename" . }}
      app.kubernetes.io/component: {{ include "diode.ingester.servicename" . }}
  template:
    metadata:
      annotations:
        checksum/config-ingester: {{ include (printf "%s/diode-ingester-configmap.yaml" $.Template.BasePath) . | sha256sum }}
      labels:
        {{- include "diode.selectorlabels" . | nindent 8 }}
        app: {{ include "diode.ingester.servicename" . }}
        app.kubernetes.io/component: {{ include "diode.ingester.servicename" . }}
    spec:
      serviceAccountName: {{ include "diode.ingester.serviceaccountname" . }}
      {{- if .Values.diodeIngester.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.diodeIngester.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.global.diode.ingester.waitForRedis }}
        - name: wait-for-redis
          image: {{ include "diode.busybox.image" . }}
          imagePullPolicy: {{ include "diode.busybox.imagepullpolicy" . }}
          command:
            - sh
            - -c
            - |
              until nc -z {{ include "diode.redis.hostname" . }} {{ include "diode.redis.port" . }}; do
                echo "Waiting for Redis server";
                sleep 3;
              done;
              echo "Redis server is up and running";
        {{- end }}
        {{- if .Values.diodeIngester.extraInitContainers }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.diodeIngester.extraInitContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "diode.ingester.servicename" . }}
          image: "{{ .Values.diodeIngester.image.repository }}:{{ .Values.diodeIngester.image.tag }}"
          imagePullPolicy: {{ .Values.diodeIngester.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.diodeIngester.containerPort | default 8081 }}
          {{- with .Values.diodeIngester.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.diodeIngester.resources }}
          resources:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- if .Values.diodeIngester.extraEnvs }}
          env: {{- include "common.tplvalues.render" (dict "value" .Values.diodeIngester.extraEnvs "context" $) | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "diode.ingester.configmap" . }}
            - secretRef:
                name: {{ include "diode.ingester.secret" . }}

{{- end }} 
