{{ if not .Values.diodeReconciler.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.diodeReconciler.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  REDIS_PASSWORD: {{ .Values.diodeReconciler.secrets.redisPassword | quote }}
{{- end -}}
