{{ if not .Values.diodeReconciler.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.diodeReconciler.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  DIODE_TO_NETBOX_API_KEY: {{ .Values.diodeReconciler.secrets.diodeToNetboxAPIKey | quote }}
  NETBOX_TO_DIODE_API_KEY: {{ .Values.diodeReconciler.secrets.netboxToDiodeAPIKey | quote }}
  DIODE_API_KEY: {{ .Values.diodeReconciler.secrets.diodeAPIKey | quote }}
  INGESTER_TO_RECONCILER_API_KEY: {{ .Values.diodeReconciler.secrets.ingesterToReconcilerAPIKey | quote }}
  REDIS_PASSWORD: {{ .Values.diodeReconciler.secrets.redisPassword | quote }}
{{- end -}}
