{{ if not .Values.diodeIngester.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.diodeIngester.serviceName }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  INGESTER_TO_RECONCILER_API_KEY: {{ .Values.diodeIngester.secrets.ingesterToReconcilerAPIKey | quote }}
  REDIS_PASSWORD: {{ .Values.diodeIngester.secrets.redisPassword | quote }}
{{- end -}}
