{{- if .Values.diodeReconciler.enabled -}}
{{- $config := index .Values.diodeReconciler.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diode.reconciler.configmap" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "diode.reconciler.servicename" . }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  GRPC_PORT: {{ .Values.diodeReconciler.containerPort | default "8081" | quote }}
  LOGGING_LEVEL: {{ $config.loggingLevel | default "INFO" | quote }}
  SENTRY_DSN: {{ $config.sentryDsn | quote }}
  REDIS_HOST: {{ include "diode.redis.hostname" . | quote }}
  REDIS_PORT: {{ include "diode.redis.port" . | quote }}
  REDIS_USERNAME: {{ include "diode.redis.username" . | quote }}
  REDIS_DB: {{ $config.redisDb | default "0" | quote }}
  REDIS_STREAM_DB: {{ $config.redisStreamDb | default "1" | quote }}
  {{- if and .Values.externalRedis.tls .Values.externalRedis.tls.enabled }}
  REDIS_TLS_ENABLED: "true"
  REDIS_TLS_SKIP_VERIFY: {{ .Values.externalRedis.tls.skipVerify | default false | quote }}
  REDIS_TLS_CA_PATH: {{ .Values.externalRedis.tls.caPath | default "" | quote }}
  REDIS_TLS_CLIENT_KEY_PATH: {{ .Values.externalRedis.tls.clientKeyPath | default "" | quote }}
  REDIS_TLS_CLIENT_CERT_PATH: {{ .Values.externalRedis.tls.clientCertPath | default "" | quote }}
  {{- end }}
  MIGRATION_ENABLED: {{ $config.migrationEnabled | default "true" | quote }}
  AUTO_APPLY_CHANGESETS: {{ $config.autoApplyChangesets | default "true" | quote }}
  RECONCILER_RATE_LIMITER_RPS: {{ $config.reconcilerRateLimiterRps | default "20" | quote }}
  RECONCILER_RATE_LIMITER_BURST: {{ $config.reconcilerRateLimiterBurst | default "1" | quote }}
  DIODE_TO_NETBOX_RATE_LIMITER_RPS: {{ $config.diodeToNetboxRateLimiterRps | default "20" | quote }}
  DIODE_TO_NETBOX_RATE_LIMITER_BURST: {{ $config.diodeToNetboxRateLimiterBurst | default "1" | quote }}
  POSTGRES_HOST: {{ include "diode.postgresql.hostname" . | quote }}
  POSTGRES_PORT: {{ include "diode.postgresql.port" . | quote }}
  POSTGRES_DB_NAME: {{ include "diode.postgresql.database" . | quote }}
  POSTGRES_USER: {{ include "diode.postgresql.username" . | quote }}
  POSTGRES_SSL_MODE: {{ include "diode.postgresql.sslMode" . | quote }}
  NETBOX_DIODE_PLUGIN_API_BASE_URL: {{ $config.netboxDiodePluginApiBaseUrl | quote }}
  NETBOX_DIODE_PLUGIN_SKIP_TLS_VERIFY: {{ $config.netboxDiodePluginSkipTlsVerify | quote }}
  DIODE_AUTH_TOKEN_URL: {{ printf "%s/token" (include "diode.auth.url" .) | quote }}
  DIODE_TO_NETBOX_CLIENT_ID: {{ $config.diodeToNetBoxClientId | quote }}
  TELEMETRY_METRICS_EXPORTER: {{ $config.telemetryMetricsExporter | quote }}
  TELEMETRY_TRACES_EXPORTER: {{ $config.telemetryTracesExporter | default "none" | quote }}
  TELEMETRY_ENVIRONMENT: {{ $config.telemetryEnvironment | default .Values.diode.environment | quote }}
{{- end }}
