{{- if and .Values.diodeIngester.enabled .Values.diodeIngester.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diode.ingester.serviceaccountname" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "diode.ingester.servicename" . }}
{{- end }} 
