{{- if .Values.diodeIngester.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.diodeIngester.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.diodeIngester.serviceName }}
{{- end -}}
