{{- if .Values.diodeAuth.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diode.auth.servicename" . }}
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app: {{ include "diode.auth.servicename" . }}
    app.kubernetes.io/component: {{ include "diode.auth.servicename" . }}
  {{- if or .Values.global.commonAnnotations .Values.diodeAuth.annotations }}
  annotations:
    {{- if .Values.diodeAuth.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.diodeAuth.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{-  end }}
spec:
  replicas: {{ .Values.diodeAuth.replicaCount }}
  selector:
    matchLabels:
      {{- include "diode.selectorlabels" . | nindent 6 }}
      app: {{ include "diode.auth.servicename" . }}
      app.kubernetes.io/component: {{ include "diode.auth.servicename" . }}
  template:
    metadata:
      annotations:
        checksum/config-auth: {{ include (printf "%s/diode-auth-configmap.yaml" $.Template.BasePath) . | sha256sum }}
      labels:
        {{- include "diode.selectorlabels" . | nindent 8 }}
        app: {{ include "diode.auth.servicename" . }}
        app.kubernetes.io/component: {{ include "diode.auth.servicename" . }}
    spec:
      serviceAccountName: {{ include "diode.auth.serviceaccountname" . }}
      {{- if .Values.diodeAuth.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.diodeAuth.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.hydra.enabled }}
        - name: wait-for-oauth2-server
          image: {{ include "diode.busybox.image" . }}
          imagePullPolicy: {{ include "diode.busybox.imagepullpolicy" . }}
          command:
            - sh
            - -c
            - |
              host={{ include "diode.hydra.public.hostname" . }}
              port={{ include "diode.hydra.public.port" . }}
              until nc -z $host $port; do
                echo "Waiting for OAuth2 server";
                sleep 3;
              done;
              echo "OAuth2 server is up and running";
        {{- end }}
        {{- if .Values.diodeAuth.extraInitContainers }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.diodeAuth.extraInitContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "diode.auth.servicename" . }}
          image: "{{ .Values.diodeAuth.image.repository }}:{{ .Values.diodeAuth.image.tag }}"
          imagePullPolicy: {{ .Values.diodeAuth.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.diodeAuth.containerPort }}
          {{- with .Values.diodeAuth.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.diodeAuth.resources }}
          resources:
            {{- toYaml .| nindent 12 }}
          {{- end }}
          {{- if .Values.diodeAuth.extraEnvs }}
          env: {{- include "common.tplvalues.render" (dict "value" .Values.diodeAuth.extraEnvs "context" $) | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "diode.auth.configmap" . }}
{{- end }} 
