{{- $ingressNginx := index .Values.ingressNginx -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "diode.ingress.name" . }}-grpc
  namespace: {{ include "diode.namespace" . }}
  labels:
    {{- include "diode.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "diode.ingress.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://{{ include "diode.auth.hostname" . }}:{{ .Values.diodeAuth.containerPort }}/introspect"
    nginx.ingress.kubernetes.io/auth-method: "POST"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- with $ingressNginx.grpcAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $ingressNginx.ingressClass | default "nginx" }}
  rules:
    - {{- if $ingressNginx.hostname  }}
      host: {{ $ingressNginx.hostname | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ include "diode.ingress.path" . }}/({{ include "diode.ingester.grpc.servicename" . }}.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "diode.ingester.servicename" . }}
                port:
                  number: {{ .Values.diodeIngester.containerPort }}
          - path: {{ include "diode.ingress.path" . }}/({{ include "diode.reconciler.grpc.servicename" . }}.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "diode.reconciler.servicename" . }}
                port:
                  number: {{ .Values.diodeReconciler.containerPort }}
