#!/bin/bash
set -e

# Create databases and users with privileges for each service

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Diode
    CREATE USER ${DIODE_POSTGRES_USER} WITH PASSWORD '${DIODE_POSTGRES_PASSWORD}';
    CREATE DATABASE ${DIODE_POSTGRES_DB_NAME} OWNER ${DIODE_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DIODE_POSTGRES_DB_NAME} TO ${DIODE_POSTGRES_USER};

    -- Hydra
    CREATE USER ${HYDRA_POSTGRES_USER} WITH PASSWORD '${HYDRA_POSTGRES_PASSWORD}';
    CREATE DATABASE ${HYDRA_POSTGRES_DB_NAME} OWNER ${HYDRA_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${HYDRA_POSTGRES_DB_NAME} TO ${HYDRA_POSTGRES_USER};
EOSQL
