// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TokenIssuanceGate is an autogenerated mock type for the TokenIssuanceGate type
type TokenIssuanceGate struct {
	mock.Mock
}

type TokenIssuanceGate_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuanceGate) EXPECT() *TokenIssuanceGate_Expecter {
	return &TokenIssuanceGate_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: ctx, clientID
func (_m *TokenIssuanceGate) Allow(ctx context.Context, clientID string) (bool, error) {
	ret := _m.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, clientID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenIssuanceGate_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type TokenIssuanceGate_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *TokenIssuanceGate_Expecter) Allow(ctx interface{}, clientID interface{}) *TokenIssuanceGate_Allow_Call {
	return &TokenIssuanceGate_Allow_Call{Call: _e.mock.On("Allow", ctx, clientID)}
}

func (_c *TokenIssuanceGate_Allow_Call) Run(run func(ctx context.Context, clientID string)) *TokenIssuanceGate_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenIssuanceGate_Allow_Call) Return(_a0 bool, _a1 error) *TokenIssuanceGate_Allow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenIssuanceGate_Allow_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *TokenIssuanceGate_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenIssuanceGate creates a new instance of TokenIssuanceGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuanceGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuanceGate {
	mock := &TokenIssuanceGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
