// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// TokenParser is an autogenerated mock type for the TokenParser type
type TokenParser struct {
	mock.Mock
}

type TokenParser_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenParser) EXPECT() *TokenParser_Expecter {
	return &TokenParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: tokenString, keyfunc
func (_m *TokenParser) Parse(tokenString string, keyfunc jwt.Keyfunc) (*jwt.Token, error) {
	ret := _m.Called(tokenString, keyfunc)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string, jwt.Keyfunc) (*jwt.Token, error)); ok {
		return rf(tokenString, keyfunc)
	}
	if rf, ok := ret.Get(0).(func(string, jwt.Keyfunc) *jwt.Token); ok {
		r0 = rf(tokenString, keyfunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string, jwt.Keyfunc) error); ok {
		r1 = rf(tokenString, keyfunc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type TokenParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
//   - keyfunc jwt.Keyfunc
func (_e *TokenParser_Expecter) Parse(tokenString interface{}, keyfunc interface{}) *TokenParser_Parse_Call {
	return &TokenParser_Parse_Call{Call: _e.mock.On("Parse", tokenString, keyfunc)}
}

func (_c *TokenParser_Parse_Call) Run(run func(tokenString string, keyfunc jwt.Keyfunc)) *TokenParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(jwt.Keyfunc))
	})
	return _c
}

func (_c *TokenParser_Parse_Call) Return(_a0 *jwt.Token, _a1 error) *TokenParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenParser_Parse_Call) RunAndReturn(run func(string, jwt.Keyfunc) (*jwt.Token, error)) *TokenParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenParser creates a new instance of TokenParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParser {
	mock := &TokenParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
