// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/netboxlabs/diode/diode-server/auth"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// TokenOwnershipProvider is an autogenerated mock type for the TokenOwnershipProvider type
type TokenOwnershipProvider struct {
	mock.Mock
}

type TokenOwnershipProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenOwnershipProvider) EXPECT() *TokenOwnershipProvider_Expecter {
	return &TokenOwnershipProvider_Expecter{mock: &_m.Mock}
}

// TokenOwnerID provides a mock function with given fields: ctx, token
func (_m *TokenOwnershipProvider) TokenOwnerID(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for TokenOwnerID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenOwnershipProvider_TokenOwnerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenOwnerID'
type TokenOwnershipProvider_TokenOwnerID_Call struct {
	*mock.Call
}

// TokenOwnerID is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenOwnershipProvider_Expecter) TokenOwnerID(ctx interface{}, token interface{}) *TokenOwnershipProvider_TokenOwnerID_Call {
	return &TokenOwnershipProvider_TokenOwnerID_Call{Call: _e.mock.On("TokenOwnerID", ctx, token)}
}

func (_c *TokenOwnershipProvider_TokenOwnerID_Call) Run(run func(ctx context.Context, token string)) *TokenOwnershipProvider_TokenOwnerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenOwnershipProvider_TokenOwnerID_Call) Return(_a0 string, _a1 error) *TokenOwnershipProvider_TokenOwnerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenOwnershipProvider_TokenOwnerID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *TokenOwnershipProvider_TokenOwnerID_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTokenOwnership provides a mock function with given fields: data, claims
func (_m *TokenOwnershipProvider) ValidateTokenOwnership(data auth.TokenOwnershipValidationData, claims jwt.MapClaims) error {
	ret := _m.Called(data, claims)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(auth.TokenOwnershipValidationData, jwt.MapClaims) error); ok {
		r0 = rf(data, claims)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokenOwnershipProvider_ValidateTokenOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenOwnership'
type TokenOwnershipProvider_ValidateTokenOwnership_Call struct {
	*mock.Call
}

// ValidateTokenOwnership is a helper method to define mock.On call
//   - data auth.TokenOwnershipValidationData
//   - claims jwt.MapClaims
func (_e *TokenOwnershipProvider_Expecter) ValidateTokenOwnership(data interface{}, claims interface{}) *TokenOwnershipProvider_ValidateTokenOwnership_Call {
	return &TokenOwnershipProvider_ValidateTokenOwnership_Call{Call: _e.mock.On("ValidateTokenOwnership", data, claims)}
}

func (_c *TokenOwnershipProvider_ValidateTokenOwnership_Call) Run(run func(data auth.TokenOwnershipValidationData, claims jwt.MapClaims)) *TokenOwnershipProvider_ValidateTokenOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.TokenOwnershipValidationData), args[1].(jwt.MapClaims))
	})
	return _c
}

func (_c *TokenOwnershipProvider_ValidateTokenOwnership_Call) Return(_a0 error) *TokenOwnershipProvider_ValidateTokenOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenOwnershipProvider_ValidateTokenOwnership_Call) RunAndReturn(run func(auth.TokenOwnershipValidationData, jwt.MapClaims) error) *TokenOwnershipProvider_ValidateTokenOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenOwnershipProvider creates a new instance of TokenOwnershipProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenOwnershipProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenOwnershipProvider {
	mock := &TokenOwnershipProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
