# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reconciler/v1/platform.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1creconciler/v1/platform.proto\x12\rreconciler.v1\x1a\x17validate/validate.proto\"\xa9\x01\n\x08Platform\x12\x17\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02(\x01R\x02id\x12\x1d\n\x04name\x18\x02 \x01(\tB\t\xfa\x42\x06r\x04\x10\x01\x18\x64R\x04name\x12/\n\x04slug\x18\x03 \x01(\tB\x1b\xfa\x42\x18r\x16\x10\x01\x18\x64\x32\x10^[-a-zA-Z0-9_]+$R\x04slug\x12\x18\n\x07\x64isplay\x18\x04 \x01(\tR\x07\x64isplay\x12\x1a\n\x03url\x18\x05 \x01(\tB\x08\xfa\x42\x05r\x03\x88\x01\x01R\x03urlBEZCgithub.com/netboxlabs/diode/diode-server/reconciler/v1/reconcilerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reconciler.v1.platform_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals[
        'DESCRIPTOR']._serialized_options = b'ZCgithub.com/netboxlabs/diode/diode-server/reconciler/v1/reconcilerpb'
    _globals['_PLATFORM'].fields_by_name['id']._options = None
    _globals['_PLATFORM'].fields_by_name['id']._serialized_options = b'\372B\0042\002(\001'
    _globals['_PLATFORM'].fields_by_name['name']._options = None
    _globals['_PLATFORM'].fields_by_name['name']._serialized_options = b'\372B\006r\004\020\001\030d'
    _globals['_PLATFORM'].fields_by_name['slug']._options = None
    _globals['_PLATFORM'].fields_by_name[
        'slug']._serialized_options = b'\372B\030r\026\020\001\030d2\020^[-a-zA-Z0-9_]+$'
    _globals['_PLATFORM'].fields_by_name['url']._options = None
    _globals['_PLATFORM'].fields_by_name['url']._serialized_options = b'\372B\005r\003\210\001\001'
    _globals['_PLATFORM']._serialized_start = 73
    _globals['_PLATFORM']._serialized_end = 242
# @@protoc_insertion_point(module_scope)
