apiVersion: v2
name: diode
description: A Helm chart for Diode
type: application
version: 0.1.0
appVersion: "0.6.0"
home: https://github.com/netboxlabs/diode
sources:
  - https://github.com/netboxlabs/diode
maintainers:
  - name: NetBox Labs
    email: support@netboxlabs.com
    url: https://github.com/netboxlabs
dependencies:
  - name: ingress-nginx
    version: 4.11.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cert-manager
    version: 1.16.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: redis
    version: 20.1.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
