global:
  # -- diode global configuration
  diode:
    # -- busybox image configuration
    busybox:
      image: busybox:latest
      imagePullPolicy: IfNotPresent
    # -- hydra additional init containers configuration
    hydra:
      # -- wait for PostgreSQL to be reachable
      waitForPostgres: true
    ingester:
      # -- wait for Redis to be reachable
      waitForRedis: true
    reconciler:
      # -- wait for PostgreSQL to be reachable
      waitForPostgres: true
      # -- wait for Redis to be reachable
      waitForRedis: true

  # -- common annotations for all resources
  commonAnnotations: {}

  # -- common labels for all resources
  commonLabels: {}

  security:
    # bitnami vs bitnamilegacy images, see https://github.com/bitnami/charts/issues/30850
    allowInsecureImages: true

diode:
  # -- environment name
  environment: development

# External PostgreSQL configuration (optional)
externalPostgresql:
  # -- hostname
  hostname: localhost
  # -- port
  port: 5432
  # -- database name
  database: diode
  # -- username
  username: diode
  # -- password
  password: ""
  # -- ssl mode
  sslMode: ""
  # -- existing postgresql secret
  existingSecretName: ""
  # -- key of password in existing postgresql secret
  existingSecretKey: ""

# External Redis configuration (optional)
externalRedis:
  # -- hostname
  hostname: localhost
  # -- port
  port: 6379
  tls:
    # -- enable TLS
    enabled: false
    # -- skip TLS verify
    skipVerify: false
    # -- path to CA certificate to verify server
    caPath: ""
    # -- path to client private key for mutual TLS
    clientKeyPath: ""
    # -- path to client certificate for mutual TLS
    clientCertPath: ""

# Diode Auth configuration
diodeAuth:
  # -- enabled
  enabled: true
  image:
    # -- image repository
    repository: docker.io/netboxlabs/diode-auth
    # -- image tag
    tag: 1.8.0
    # -- secrets with credentials to pull images from a private registry
    imagePullSecrets: []
    # -- pull policy
    pullPolicy: IfNotPresent
  # -- replica count
  replicaCount: 1
  serviceAccount:
    # -- create service account
    create: true
  # -- port to listen on
  containerPort: 8080
  # -- resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # -- (string or list) extra environment variables to be set on containers' `env` section
  extraEnvs: []
  # -- (string or list) additional containers to run before auth finishes initializing (may contain templating instructions)
  extraInitContainers: ""
  # -- annotations to add to the auth deployment
  annotations: {}
  config:
    # -- logging level
    loggingLevel: INFO
    # -- sentry DSN
    sentryDsn: ""
    # -- telemetry metrics exporter
    telemetryMetricsExporter: prometheus
    # -- telemetry traces exporter
    telemetryTracesExporter: none
    # -- telemetry environment
    telemetryEnvironment: dev

# Diode Auth Bootstrap configuration
diodeAuthBootstrap:
  # -- enabled
  enabled: true
  image:
    # -- image repository
    repository: docker.io/netboxlabs/diode-auth
    # -- image tag
    tag: 1.8.0
    # -- secrets with credentials to pull images from a private registry
    imagePullSecrets: []
    # -- pull policy
    pullPolicy: IfNotPresent
  job:
    # -- backoff limit
    backoffLimit: 20
    # -- annotations to add to the auth bootstrap job
    annotations:
      "helm.sh/hook": post-install, post-upgrade
      "helm.sh/hook-weight": "2"
    # -- (string or list) additional initContainers to run during bootstrap (may contain templating instructions)
    extraInitContainers: ""

# Diode Ingester configuration
diodeIngester:
  # -- enabled
  enabled: true
  image:
    # -- image repository
    repository: docker.io/netboxlabs/diode-ingester
    # -- image tag
    tag: 1.9.0
    # -- secrets with credentials to pull images from a private registry
    imagePullSecrets: []
    # -- pull policy
    pullPolicy: IfNotPresent
  # -- replica count
  replicaCount: 1
  serviceAccount:
    # -- create service account
    create: true
  # -- existing secret name
  existingSecret: diode-ingester-secret
  # -- port to listen on
  containerPort: 8081
  # -- resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  grpc:
    # -- grpc service name
    serviceName: diode.v1.IngesterService
  # -- (string or list) extra environment variables to be set on containers' `env` section
  extraEnvs: []
  # -- (string or list) additional containers to run before the ingester finishes initializing (may contain templating instructions)
  extraInitContainers: ""
  # -- annotations to add to the ingester deployment
  annotations: {}
  config:
    # -- logging level
    loggingLevel: INFO
    # -- sentry DSN
    sentryDsn: ""
    # -- redis stream db
    redisStreamDb: 1
    # -- telemetry metrics exporter
    telemetryMetricsExporter: prometheus
    # -- telemetry traces exporter
    telemetryTracesExporter: none
    # -- telemetry environment
    telemetryEnvironment: dev

# Diode Reconciler configuration
diodeReconciler:
  # -- enabled
  enabled: true
  image:
    # -- image repository
    repository: docker.io/netboxlabs/diode-reconciler
    # -- image tag
    tag: 1.9.0
    # -- secrets with credentials to pull images from a private registry
    imagePullSecrets: []
    # -- pull policy
    pullPolicy: IfNotPresent
  # -- replica count
  replicaCount: 1
  serviceAccount:
    # -- create service account
    create: true
  # -- existing secret name
  existingSecret: diode-reconciler-secret
  # -- port to listen on
  containerPort: 8081
  # -- resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  grpc:
    # -- grpc service name
    serviceName: diode.v1.ReconcilerService
  # -- (string or list) extra environment variables to be set on containers' `env` section
  extraEnvs: []
  # -- (string or list) additional containers to run before the reconciler finishes initializing (may contain templating instructions)
  extraInitContainers: ""
  # -- annotations to add to the reconciler deployment
  annotations: {}
  config:
    # -- netbox diode plugin api base url
    netboxDiodePluginApiBaseUrl: http://localhost:8000/netbox/api/plugins/diode
    # -- netbox diode plugin skip tls verify
    netboxDiodePluginSkipTlsVerify: false
    # -- logging level
    loggingLevel: INFO
    # -- sentry DSN
    sentryDsn: ""
    # -- migration enabled
    migrationEnabled: "true"
    # -- auto apply changesets
    autoApplyChangesets: "true"
    # -- reconciler rate limiter rps
    reconcilerRateLimiterRps: 20
    # -- reconciler rate limiter burst
    reconcilerRateLimiterBurst: 1
    # -- diode to netbox rate limiter rps
    diodeToNetboxRateLimiterRps: 20
    # -- diode to netbox rate limiter burst
    diodeToNetboxRateLimiterBurst: 1
    # -- postgres db name
    postgresDbName: diode
    # -- postgres user
    postgresUser: diode
    # -- redis db
    redisDb: 0
    # -- redis stream db
    redisStreamDb: 1
    # -- telemetry metrics exporter
    telemetryMetricsExporter: prometheus
    # -- telemetry traces exporter
    telemetryTracesExporter: none
    # -- telemetry environment
    telemetryEnvironment: dev
    # -- diode to netbox client id
    diodeToNetBoxClientId: diode-to-netbox

# Redis configuration (optional)
# -- ref: https://github.com/bitnami/charts/tree/main/bitnami/redis
redis:
  # -- enabled
  enabled: true
  # -- fullname override
  fullnameOverride: diode-redis
  image:
    # -- image repository
    repository: bitnamilegacy/redis
  auth:
    # -- auth enabled
    enabled: true
    # -- existing secret name
    existingSecret: diode-redis-secret
    # -- existing secret password key
    existingSecretPasswordKey: redis-password
  # -- container ports
  containerPorts:
    redis: 6379
  service:
    # -- service port
    port: 6379
  replica:
    # -- replica count
    replicaCount: 1
  persistence:
    # -- persistence enabled
    enabled: true
    # -- persistence size
    size: 1Gi
  metrics:
    image:
      # -- image repository
      repository: bitnamilegacy/redis-exporter
  sentinel:
    image:
      # -- image repository
      repository: bitnamilegacy/redis-sentinel
  volumePermissions:
    image:
      # -- image repository
      repository: bitnamilegacy/os-shell
  kubectl:
    image:
      # -- image repository
      repository: bitnamilegacy/kubectl
  sysctl:
    image:
      # -- image repository
      repository: bitnamilegacy/os-shell

# PostgreSQL configuration (optional)
# -- ref: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  # -- enabled
  enabled: true
  # -- fullname override
  fullnameOverride: diode-postgresql
  image:
    # -- image repository
    repository: bitnamilegacy/postgresql
  auth:
    # -- existing secret name
    existingSecret: diode-postgresql-secret
    # -- existing secret password key
    secretKeys:
      adminPasswordKey: postgres-password
  primary:
    persistence:
      # -- persistence enabled
      enabled: true
      # -- persistence size
      size: 10Gi
    # -- extra volume mounts
    extraVolumeMounts:
      - name: custom-init-scripts
        mountPath: /docker-entrypoint-initdb.d/init_diode_databases.sh
        subPath: init_diode_databases.sh
    initdb:
      # -- scripts config map
      scriptsConfigMap: diode-postgresql-initdb-scripts-configmap
    # -- readiness probe
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
    # -- liveness probe
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
  metrics:
    image:
      # -- image repository
      repository: bitnamilegacy/postgres-exporter
  volumePermissions:
    image:
      # -- image repository
      repository: bitnamilegacy/postgresql

# Hydra configuration
# -- ref: https://github.com/ory/k8s/blob/master/helm/charts/hydra/values.yaml
hydra:
  # -- enabled
  enabled: true
  # -- fullname override
  fullnameOverride: diode-hydra
  secret:
    # -- secret enabled
    enabled: false
    # -- existing secret name
    nameOverride: diode-hydra-secret
  # Hydra chart configuration
  hydra:
    service:
      public:
        # -- public service enabled
        enabled: true
        # -- public service type
        type: ClusterIP  # Ensure service is only internal
        # -- public service port
        port: 4444
      admin:
        # -- admin service enabled
        enabled: true
        # -- admin service type
        type: ClusterIP  # Ensure service is only internal
        # -- admin service port
        port: 4445
    ingress:
      public:
        # -- public ingress enabled
        enabled: false
      admin:
        # -- admin ingress enabled
        enabled: false
    config:
      strategies:
        # -- access token strategy
        access_token: jwt
        jwt:
          # -- scope claim
          scope_claim: both
      ttl:
        # -- access token TTL
        access_token: 1h
      oidc:
        # -- subject identifiers
        subject_identifiers:
          supported_types:
            - public
      urls:
        # -- self issuer
        self:
          # -- hydra public url
          issuer: http://diode-hydra-public.{{ .Release.Namespace }}.svc.cluster.local:4444
    automigration:
      # -- automigration enabled
      enabled: true
    # -- dev mode
    dev: true  # Hydra is not exposed to the public internet
  deployment:
    # -- (string or list) extra init containers
    extraInitContainers: |-
      {{ include "diode.hydra.extrainitcontainers" . }}
    # -- resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  job:
    # -- job annotations
    annotations:
      "helm.sh/hook": post-install, post-upgrade
      "helm.sh/hook-weight": "1"
      "helm.sh/hook-delete-policy": hook-succeeded
    # -- (string or list) extra init containers
    extraInitContainers: |-
      {{ include "diode.hydra.extrainitcontainers" . }}

# Ingress Nginx Controller configuration (optional)
# -- ref: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
ingressNginx:
  # -- ingress-nginx enabled
  enabled: true
  # -- hostname
  hostname: ""
  # -- ingress class
  ingressClass: nginx
  # -- ingress annotations
  controller:
    # -- deploy an ingress-nginx controller chart in addition to `Ingress` resources
    enabled: true
    # -- allow snippet annotations
    allowSnippetAnnotations: true
  annotations: {}
  # -- ingress tls
  tls: {}
    # - secretName: diode-tls
    #   hosts:
    #     - diode.example.com
  # -- ingress http annotations
  httpAnnotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # -- ingress grpc annotations
  grpcAnnotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
  # -- ingress path prefix
  pathPrefix: /diode
  # -- ingress extra http paths
  extraHttpPaths: []
    # - path: /
    #   pathType: Prefix
    #   serviceName: netbox
    #   servicePort: 80
    # - path: /(.*)
    #   pathType: ImplementationSpecific
    #   serviceName: netbox
    #   servicePort: 80

# Cert Manager configuration (optional)
# -- ref: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
certManager:
  # -- cert-manager enabled
  enabled: false
  # -- install CRDs
  crds:
    enabled: true
  # -- cert-manager namespace
  namespace: diode-cert-manager
  # -- prometheus enabled
  prometheus:
    enabled: false
  # -- webhook enabled
  webhook:
    enabled: true
  # -- cainjector enabled
  cainjector:
    enabled: true

# Certificate issuer configuration
# -- ref: https://cert-manager.io/docs/configuration/acme/
certIssuer:
  # -- enable certificate issuer creation
  enabled: false
  # -- issuer kind (Issuer or ClusterIssuer) ref: https://cert-manager.io/docs/configuration/acme/
  kind: Issuer
  # -- issuer name
  name: letsencrypt-development
  # -- email address for Let's Encrypt notifications
  email: admin@example.com
