// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/netboxlabs/diode/diode-server/graph"

	mock "github.com/stretchr/testify/mock"
)

// NodeFinder is an autogenerated mock type for the NodeFinder type
type NodeFinder struct {
	mock.Mock
}

type NodeFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *NodeFinder) EXPECT() *NodeFinder_Expecter {
	return &NodeFinder_Expecter{mock: &_m.Mock}
}

// FindNodeByMetadata provides a mock function with given fields: ctx, arg
func (_m *NodeFinder) FindNodeByMetadata(ctx context.Context, arg graph.FindNodeByMetadataParams) (graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByMetadata")
	}

	var r0 graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodeByMetadataParams) graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(graph.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodeByMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeFinder_FindNodeByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByMetadata'
type NodeFinder_FindNodeByMetadata_Call struct {
	*mock.Call
}

// FindNodeByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodeByMetadataParams
func (_e *NodeFinder_Expecter) FindNodeByMetadata(ctx interface{}, arg interface{}) *NodeFinder_FindNodeByMetadata_Call {
	return &NodeFinder_FindNodeByMetadata_Call{Call: _e.mock.On("FindNodeByMetadata", ctx, arg)}
}

func (_c *NodeFinder_FindNodeByMetadata_Call) Run(run func(ctx context.Context, arg graph.FindNodeByMetadataParams)) *NodeFinder_FindNodeByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodeByMetadataParams))
	})
	return _c
}

func (_c *NodeFinder_FindNodeByMetadata_Call) Return(_a0 graph.Node, _a1 error) *NodeFinder_FindNodeByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeFinder_FindNodeByMetadata_Call) RunAndReturn(run func(context.Context, graph.FindNodeByMetadataParams) (graph.Node, error)) *NodeFinder_FindNodeByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodesByFieldMatch provides a mock function with given fields: ctx, arg
func (_m *NodeFinder) FindNodesByFieldMatch(ctx context.Context, arg graph.FindNodesByFieldMatchParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodesByFieldMatch")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.FindNodesByFieldMatchParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.FindNodesByFieldMatchParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeFinder_FindNodesByFieldMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodesByFieldMatch'
type NodeFinder_FindNodesByFieldMatch_Call struct {
	*mock.Call
}

// FindNodesByFieldMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.FindNodesByFieldMatchParams
func (_e *NodeFinder_Expecter) FindNodesByFieldMatch(ctx interface{}, arg interface{}) *NodeFinder_FindNodesByFieldMatch_Call {
	return &NodeFinder_FindNodesByFieldMatch_Call{Call: _e.mock.On("FindNodesByFieldMatch", ctx, arg)}
}

func (_c *NodeFinder_FindNodesByFieldMatch_Call) Run(run func(ctx context.Context, arg graph.FindNodesByFieldMatchParams)) *NodeFinder_FindNodesByFieldMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.FindNodesByFieldMatchParams))
	})
	return _c
}

func (_c *NodeFinder_FindNodesByFieldMatch_Call) Return(_a0 []graph.Node, _a1 error) *NodeFinder_FindNodesByFieldMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeFinder_FindNodesByFieldMatch_Call) RunAndReturn(run func(context.Context, graph.FindNodesByFieldMatchParams) ([]graph.Node, error)) *NodeFinder_FindNodesByFieldMatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodesByType provides a mock function with given fields: ctx, arg
func (_m *NodeFinder) GetNodesByType(ctx context.Context, arg graph.GetNodesByTypeParams) ([]graph.Node, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetNodesByType")
	}

	var r0 []graph.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, graph.GetNodesByTypeParams) []graph.Node); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]graph.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, graph.GetNodesByTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NodeFinder_GetNodesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodesByType'
type NodeFinder_GetNodesByType_Call struct {
	*mock.Call
}

// GetNodesByType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg graph.GetNodesByTypeParams
func (_e *NodeFinder_Expecter) GetNodesByType(ctx interface{}, arg interface{}) *NodeFinder_GetNodesByType_Call {
	return &NodeFinder_GetNodesByType_Call{Call: _e.mock.On("GetNodesByType", ctx, arg)}
}

func (_c *NodeFinder_GetNodesByType_Call) Run(run func(ctx context.Context, arg graph.GetNodesByTypeParams)) *NodeFinder_GetNodesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(graph.GetNodesByTypeParams))
	})
	return _c
}

func (_c *NodeFinder_GetNodesByType_Call) Return(_a0 []graph.Node, _a1 error) *NodeFinder_GetNodesByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NodeFinder_GetNodesByType_Call) RunAndReturn(run func(context.Context, graph.GetNodesByTypeParams) ([]graph.Node, error)) *NodeFinder_GetNodesByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewNodeFinder creates a new instance of NodeFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeFinder {
	mock := &NodeFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
