// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	postgres "github.com/netboxlabs/diode/diode-server/gen/dbstore/postgres"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindNodeByMetadata provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNodeByMetadata(ctx context.Context, arg postgres.FindNodeByMetadataParams) (postgres.GraphNode, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodeByMetadata")
	}

	var r0 postgres.GraphNode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.FindNodeByMetadataParams) (postgres.GraphNode, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, postgres.FindNodeByMetadataParams) postgres.GraphNode); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(postgres.GraphNode)
	}

	if rf, ok := ret.Get(1).(func(context.Context, postgres.FindNodeByMetadataParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNodeByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodeByMetadata'
type Repository_FindNodeByMetadata_Call struct {
	*mock.Call
}

// FindNodeByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.FindNodeByMetadataParams
func (_e *Repository_Expecter) FindNodeByMetadata(ctx interface{}, arg interface{}) *Repository_FindNodeByMetadata_Call {
	return &Repository_FindNodeByMetadata_Call{Call: _e.mock.On("FindNodeByMetadata", ctx, arg)}
}

func (_c *Repository_FindNodeByMetadata_Call) Run(run func(ctx context.Context, arg postgres.FindNodeByMetadataParams)) *Repository_FindNodeByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.FindNodeByMetadataParams))
	})
	return _c
}

func (_c *Repository_FindNodeByMetadata_Call) Return(_a0 postgres.GraphNode, _a1 error) *Repository_FindNodeByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNodeByMetadata_Call) RunAndReturn(run func(context.Context, postgres.FindNodeByMetadataParams) (postgres.GraphNode, error)) *Repository_FindNodeByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// FindNodesByFieldMatch provides a mock function with given fields: ctx, arg
func (_m *Repository) FindNodesByFieldMatch(ctx context.Context, arg postgres.FindNodesByFieldMatchParams) ([]postgres.GraphNode, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindNodesByFieldMatch")
	}

	var r0 []postgres.GraphNode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.FindNodesByFieldMatchParams) ([]postgres.GraphNode, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, postgres.FindNodesByFieldMatchParams) []postgres.GraphNode); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.GraphNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, postgres.FindNodesByFieldMatchParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindNodesByFieldMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNodesByFieldMatch'
type Repository_FindNodesByFieldMatch_Call struct {
	*mock.Call
}

// FindNodesByFieldMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.FindNodesByFieldMatchParams
func (_e *Repository_Expecter) FindNodesByFieldMatch(ctx interface{}, arg interface{}) *Repository_FindNodesByFieldMatch_Call {
	return &Repository_FindNodesByFieldMatch_Call{Call: _e.mock.On("FindNodesByFieldMatch", ctx, arg)}
}

func (_c *Repository_FindNodesByFieldMatch_Call) Run(run func(ctx context.Context, arg postgres.FindNodesByFieldMatchParams)) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.FindNodesByFieldMatchParams))
	})
	return _c
}

func (_c *Repository_FindNodesByFieldMatch_Call) Return(_a0 []postgres.GraphNode, _a1 error) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindNodesByFieldMatch_Call) RunAndReturn(run func(context.Context, postgres.FindNodesByFieldMatchParams) ([]postgres.GraphNode, error)) *Repository_FindNodesByFieldMatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetGraphNodesByType provides a mock function with given fields: ctx, arg
func (_m *Repository) GetGraphNodesByType(ctx context.Context, arg postgres.GetGraphNodesByTypeParams) ([]postgres.GraphNode, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetGraphNodesByType")
	}

	var r0 []postgres.GraphNode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.GetGraphNodesByTypeParams) ([]postgres.GraphNode, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, postgres.GetGraphNodesByTypeParams) []postgres.GraphNode); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.GraphNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, postgres.GetGraphNodesByTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetGraphNodesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraphNodesByType'
type Repository_GetGraphNodesByType_Call struct {
	*mock.Call
}

// GetGraphNodesByType is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.GetGraphNodesByTypeParams
func (_e *Repository_Expecter) GetGraphNodesByType(ctx interface{}, arg interface{}) *Repository_GetGraphNodesByType_Call {
	return &Repository_GetGraphNodesByType_Call{Call: _e.mock.On("GetGraphNodesByType", ctx, arg)}
}

func (_c *Repository_GetGraphNodesByType_Call) Run(run func(ctx context.Context, arg postgres.GetGraphNodesByTypeParams)) *Repository_GetGraphNodesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(postgres.GetGraphNodesByTypeParams))
	})
	return _c
}

func (_c *Repository_GetGraphNodesByType_Call) Return(_a0 []postgres.GraphNode, _a1 error) *Repository_GetGraphNodesByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetGraphNodesByType_Call) RunAndReturn(run func(context.Context, postgres.GetGraphNodesByTypeParams) ([]postgres.GraphNode, error)) *Repository_GetGraphNodesByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
