mockname: "{{.InterfaceName}}"
structname: "{{.InterfaceName}}.go"
filename: "{{.InterfaceName | lower }}.go"
with-expecter: true
packages:
  github.com/netboxlabs/diode/diode-server/netboxdiodeplugin:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
  github.com/netboxlabs/diode/diode-server/reconciler:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
