mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | lower }}.go"
with-expecter: true
issue-845-fix: true
resolve-type-alias: False
packages:
  github.com/netboxlabs/diode/diode-server/netboxdiodeplugin:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
  github.com/netboxlabs/diode/diode-server/ingester:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
  github.com/netboxlabs/diode/diode-server/reconciler:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
      exclude:
        - ProcessorOption
  github.com/netboxlabs/diode/diode-server/auth:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
  github.com/netboxlabs/diode/diode-server/telemetry:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
