FROM alpine:3.21

RUN apk add --no-cache jq

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --chown=appuser:addgroup --from=oryd/hydra:v2.3.0 /usr/bin/hydra /usr/bin/hydra

ARG SVC

COPY --chown=appuser:appgroup build/$SVC /usr/local/bin/diode-server

USER appuser

LABEL maintainer="techops@netboxlabs.com"
LABEL org.opencontainers.image.title="Diode $SVC"
LABEL org.opencontainers.image.url="https://github.com/netboxlabs/diode"
LABEL org.opencontainers.image.documentation="https://github.com/netboxlabs/diode"
LABEL org.opencontainers.image.description="NetBox Labs diode $SVC image"
LABEL org.opencontainers.image.vendor="NetBox Labs, Inc"
LABEL org.opencontainers.image.authors="techops@netboxlabs.com"
LABEL org.opencontainers.image.licenses="PolyForm Shield License 1.0.0"

CMD ["/usr/local/bin/diode-server"]
