ARG GO_VERSION=1.26

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS build

COPY . /app
WORKDIR /app

ARG TARGETOS TARGETARCH SVC

RUN --mount=target=. \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /build/$SVC ./cmd/$SVC

RUN --mount=target=. \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /build/authmanager ./cmd/authmanager


FROM alpine:3.22

RUN apk upgrade --no-cache && apk add --no-cache jq

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --chown=appuser:appgroup --from=oryd/hydra:v26.2.0@sha256:ff67c7fb5f95074fa53374d41151713554960504b340cd3f95b09e65deaea2a9 /usr/bin/hydra /usr/bin/hydra

ARG SVC

COPY --chown=appuser:appgroup --from=build /build/$SVC /usr/local/bin/diode-server
COPY --chown=appuser:appgroup --from=build /build/authmanager /usr/local/bin/authmanager
COPY --chown=appuser:appgroup --from=build /app/docker/oauth2/bootstrap-clients.sh /etc/config/oauth2/

RUN chmod +x /etc/config/oauth2/bootstrap-clients.sh

USER appuser

LABEL maintainer="techops@netboxlabs.com"
LABEL org.opencontainers.image.title="Diode $SVC"
LABEL org.opencontainers.image.url="https://github.com/netboxlabs/diode"
LABEL org.opencontainers.image.documentation="https://github.com/netboxlabs/diode"
LABEL org.opencontainers.image.description="NetBox Labs diode $SVC image"
LABEL org.opencontainers.image.vendor="NetBox Labs, Inc"
LABEL org.opencontainers.image.authors="techops@netboxlabs.com"
LABEL org.opencontainers.image.licenses="NetBox Limited Use License 1.0"

CMD ["/usr/local/bin/diode-server"]
