name: Go - lint
on:
  push:
    branches:
      - "!release"
    paths:
      - "diode-server/**"
  pull_request:
    paths:
      - "diode-server/**"

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: diode-server
          args: --config ../.github/golangci.yaml
          skip-pkg-cache: true
          skip-build-cache: true
