name: Helm - release
on:
  workflow_dispatch:
  push:
    branches: [ release ]
    paths:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  helm-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: charts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
      - name: Extract Helm repo dependencies from Chart.yaml
        id: extract_repos
        uses: mikefarah/yq@b534aa9ee5d38001fba3cd8fe254a037e4847b37 # v4.45.4
        with:
          cmd: yq -o=tsv '.dependencies[] | [.name, .repository] | @tsv' charts/diode/Chart.yaml
      - name: Add Helm repos from dependencies
        run: |
          echo "${{ steps.extract_repos.outputs.result }}" | while IFS=$'\t' read -r name repo; do
            helm repo add "$name" "$repo"
          done      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: helm-chart-{{ .Name }}-{{ .Version }}
          CR_INDEX_PATH: charts/index.yaml
          CR_PAGES_INDEX_PATH: charts/index.yaml
