name: Helm - lint
on:
  push:
    branches:
      - "!release"
    paths:
      - "charts/**"
  pull_request:
    paths:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: charts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
      - name: Update helm dependencies
        run: helm dependency update diode
      - name: Run helm lint
        run: helm lint diode
