name: Server - release
on:
  workflow_dispatch:
  push:
    branches: [ release ]
    paths:
      - "diode-server/**"
      - "!diode-server/docker/**"
      - "!diode-server/Makefile"
      - "!diode-server/README.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SEMANTIC_RELEASE_PACKAGE: ${{ github.repository }}
  GO_VERSION: '1.24'
  JF_REPOSITORY: obs-builds

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}
    steps:
      - name: Get apps
        id: apps
        run: |
          echo 'apps=["auth", "ingester", "reconciler"]' >> "$GITHUB_OUTPUT"

  get-next-version:
    name: Get next version - ${{ matrix.app }}
    needs: [ setup ]
    uses: netboxlabs/diode/.github/workflows/reusable_semantic_release_get_next_version.yaml@develop
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.setup.outputs.apps) }}
    with:
      app_name: diode-${{ matrix.app }}
      app_dir: diode-server
    secrets: inherit

  build:
    name: Build - ${{ matrix.app }}
    needs: [ setup, get-next-version ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.setup.outputs.apps) }}
    if: needs.get-next-version.outputs.new-release-published == 'true'
    env:
      APP_NAME: diode-${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short sha
        id: short-sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version-${{ env.APP_NAME }}_${{ env.SHORT_SHA }}
          path: ./versions

      - name: Set build version
        run: |
          BUILD_VERSION=$(cat ./versions/${{ env.APP_NAME }}_${{ env.SHORT_SHA }}.txt)
          # error if BUILD_VERSION is empty
          if [ -z "$BUILD_VERSION" ]; then
            echo "BUILD_VERSION is empty, exiting"
            exit 1
          fi
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
          echo "BUILD_COMMIT=${{ env.SHORT_SHA }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup JFrog CLI
        id: setup-jfrog-cli
        uses: jfrog/setup-jfrog-cli@ff5cb544114ffc152db9cea1cd3d5978d5074946 # v4.5.11
        env:
          JF_URL: https://netboxlabs.jfrog.io
          JF_PROJECT: obs
        with:
          oidc-provider-name: github-ci

      - name: Login to JFrog Artifactory
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3
        with:
          registry: netboxlabs.jfrog.io
          username: ${{ steps.setup-jfrog-cli.outputs.oidc-user }}
          password: ${{ steps.setup-jfrog-cli.outputs.oidc-token }}

      - name: Set build info
        run: |
          echo $BUILD_COMMIT > ./diode-server/version/BUILD_COMMIT.txt
          echo $BUILD_VERSION > ./diode-server/version/BUILD_VERSION.txt

      - name: Build image and push
        id: docker-build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: diode-server
          file: diode-server/docker/Dockerfile-build.${{ matrix.app }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            netboxlabs/${{ env.APP_NAME }}:latest
            netboxlabs/${{ env.APP_NAME }}:${{ env.BUILD_VERSION }}
            netboxlabs.jfrog.io/${{ env.JF_REPOSITORY }}/${{ env.APP_NAME }}:latest
            netboxlabs.jfrog.io/${{ env.JF_REPOSITORY }}/${{ env.APP_NAME }}:${{ env.BUILD_VERSION }}
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            SVC=${{ matrix.app }}

      - name: Create and publish JFrog build
        run: |
          DIGEST="${{ steps.docker-build.outputs.digest }}"
          IMAGE_TAG="netboxlabs.jfrog.io/${{ env.JF_REPOSITORY }}/${{ env.APP_NAME }}:${{ env.BUILD_VERSION }}@${DIGEST}"
          echo "${IMAGE_TAG}" > build-metadata
          jf rt build-docker-create ${{ env.JF_REPOSITORY }} --image-file build-metadata --build-name ${{ env.APP_NAME }} --build-number ${{ env.BUILD_VERSION }}
          jf rt build-publish ${{ env.APP_NAME }} ${{ env.BUILD_VERSION }}

  semantic-release:
    name: Semantic release - ${{ matrix.app }}
    uses: netboxlabs/diode/.github/workflows/reusable_semantic_release.yaml@develop
    needs: [ setup, build ]
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.setup.outputs.apps) }}
    with:
      app_name: diode-${{ matrix.app }}
      app_dir: diode-server
    secrets: inherit
