name: diode-netbox-plugin
services:
  netbox: &netbox
    image: netboxcommunity/netbox:v4.0-2.9.1-diode-netbox-plugin
    build:
      context: .
      dockerfile: Dockerfile-diode-netbox-plugin
      pull: true
    depends_on:
      - netbox-postgres
      - netbox-redis
      - netbox-redis-cache
    env_file: netbox/env/netbox.env
    user: 'unit:root'
    healthcheck:
      start_period: 60s
      timeout: 3s
      interval: 15s
      test: "curl -f http://localhost:8080/netbox/api/ || exit 1"
    volumes:
      - ./netbox/docker-entrypoint.sh:/opt/netbox/docker-entrypoint.sh:z,ro
      - ./netbox/nginx-unit.json:/opt/netbox/nginx-unit.json:z,ro
      - ../netbox_diode_plugin:/opt/netbox/netbox/netbox_diode_plugin:ro
      - ./netbox/launch-netbox.sh:/opt/netbox/launch-netbox.sh:z,ro
      - ./coverage:/opt/netbox/netbox/coverage:z,rw
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
    ports:
      - "8000:8080"

  # postgres
  netbox-postgres:
    image: docker.io/postgres:16-alpine
    env_file: netbox/env/postgres.env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data

  # redis
  netbox-redis:
    image: docker.io/redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: netbox/env/redis.env
    volumes:
      - netbox-redis-data:/data

  netbox-redis-cache:
    image: docker.io/redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: netbox/env/redis-cache.env
    volumes:
      - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local
